// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_IllustratedScreen_screen_init(void)
{
    ui_IllustratedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IllustratedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_illustratedbg = lv_img_create(ui_IllustratedScreen);
    lv_img_set_src(ui_illustratedbg, &ui_img_letterbg__png);
    lv_obj_set_width(ui_illustratedbg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_illustratedbg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_illustratedbg, -4);
    lv_obj_set_y(ui_illustratedbg, 5);
    lv_obj_set_align(ui_illustratedbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_illustratedbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_illustratedbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_illustratedbg, 600);

    ui_illuTextArea = lv_textarea_create(ui_IllustratedScreen);
    lv_obj_set_width(ui_illuTextArea, 467);
    lv_obj_set_height(ui_illuTextArea, 374);
    lv_obj_set_x(ui_illuTextArea, 77);
    lv_obj_set_y(ui_illuTextArea, 8);
    lv_obj_set_align(ui_illuTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_illuTextArea, "Placeholder...");
    lv_obj_set_style_text_font(ui_illuTextArea, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_illuTextArea, lv_color_hex(0xFFE2AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_illuTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_illuImage = lv_img_create(ui_IllustratedScreen);
    lv_img_set_src(ui_illuImage, &ui_img_uppercaveplants__png);
    lv_obj_set_width(ui_illuImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_illuImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_illuImage, -27);
    lv_obj_set_y(ui_illuImage, -212);
    lv_obj_set_align(ui_illuImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_illuImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_illuImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_illuImage, 120);

    ui_back = lv_img_create(ui_IllustratedScreen);
    lv_img_set_src(ui_back, &ui_img_zen_prevgarden_png);
    lv_obj_set_width(ui_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_back, -345);
    lv_obj_set_y(ui_back, -179);
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_illplant = lv_obj_create(ui_IllustratedScreen);
    lv_obj_remove_style_all(ui_illplant);
    lv_obj_set_width(ui_illplant, 191);
    lv_obj_set_height(ui_illplant, 262);
    lv_obj_set_x(ui_illplant, -262);
    lv_obj_set_y(ui_illplant, -14);
    lv_obj_set_align(ui_illplant, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_illplant, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sunflower = lv_img_create(ui_illplant);
    lv_img_set_src(ui_sunflower, &ui_img_sunflower_png);
    lv_obj_set_width(ui_sunflower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower, 5);
    lv_obj_set_y(ui_sunflower, -15);
    lv_obj_set_align(ui_sunflower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sunflower, 150);

    ui_Label2 = lv_label_create(ui_illplant);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -4);
    lv_obj_set_y(ui_Label2, 118);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "向日葵");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back, ui_event_back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower, ui_event_sunflower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label2, ui_event_Label2, LV_EVENT_ALL, NULL);

}
