// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calculator = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_calculator);
    lv_obj_set_width(ui_calculator, 338);
    lv_obj_set_height(ui_calculator, 340);
    lv_obj_set_x(ui_calculator, -44);
    lv_obj_set_y(ui_calculator, 34);
    lv_obj_set_align(ui_calculator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_calculator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_calculator, lv_color_hex(0xD1CCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calculator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button7, 54);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -123);
    lv_obj_set_y(ui_Button7, -75);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "7");

    ui_Button8 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button8, 54);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -45);
    lv_obj_set_y(ui_Button8, -75);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "8");

    ui_Button9 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button9, 54);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, 33);
    lv_obj_set_y(ui_Button9, -75);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "9");

    ui_Button4 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button4, 54);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -123);
    lv_obj_set_y(ui_Button4, -6);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "4");

    ui_Button5 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button5, 54);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -45);
    lv_obj_set_y(ui_Button5, -6);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "5");

    ui_Button6 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button6, 54);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 32);
    lv_obj_set_y(ui_Button6, -6);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "6");

    ui_Button1 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button1, 54);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -123);
    lv_obj_set_y(ui_Button1, 63);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "1");

    ui_Button2 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button2, 54);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -45);
    lv_obj_set_y(ui_Button2, 63);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "2");

    ui_Button3 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button3, 54);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 32);
    lv_obj_set_y(ui_Button3, 63);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "3");

    ui_Button0 = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Button0, 54);
    lv_obj_set_height(ui_Button0, 50);
    lv_obj_set_x(ui_Button0, -123);
    lv_obj_set_y(ui_Button0, 130);
    lv_obj_set_align(ui_Button0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label0 = lv_label_create(ui_Button0);
    lv_obj_set_width(ui_Label0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label0, "0");

    ui_Buttonmul = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Buttonmul, 54);
    lv_obj_set_height(ui_Buttonmul, 50);
    lv_obj_set_x(ui_Buttonmul, -45);
    lv_obj_set_y(ui_Buttonmul, 130);
    lv_obj_set_align(ui_Buttonmul, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonmul, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonmul, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonmul, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonmul, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelmul = lv_label_create(ui_Buttonmul);
    lv_obj_set_width(ui_Labelmul, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelmul, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelmul, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmul, "*");

    ui_Buttondiv = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Buttondiv, 54);
    lv_obj_set_height(ui_Buttondiv, 50);
    lv_obj_set_x(ui_Buttondiv, 32);
    lv_obj_set_y(ui_Buttondiv, 130);
    lv_obj_set_align(ui_Buttondiv, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttondiv, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttondiv, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttondiv, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttondiv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeldiv = lv_label_create(ui_Buttondiv);
    lv_obj_set_width(ui_Labeldiv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldiv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labeldiv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldiv, "/");

    ui_Buttondel = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Buttondel, 54);
    lv_obj_set_height(ui_Buttondel, 50);
    lv_obj_set_x(ui_Buttondel, 120);
    lv_obj_set_y(ui_Buttondel, -75);
    lv_obj_set_align(ui_Buttondel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttondel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttondel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttondel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttondel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeldel = lv_label_create(ui_Buttondel);
    lv_obj_set_width(ui_Labeldel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labeldel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldel, "del");

    ui_Buttonadd = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Buttonadd, 54);
    lv_obj_set_height(ui_Buttonadd, 50);
    lv_obj_set_x(ui_Buttonadd, 120);
    lv_obj_set_y(ui_Buttonadd, -5);
    lv_obj_set_align(ui_Buttonadd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonadd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonadd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonadd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeladd = lv_label_create(ui_Buttonadd);
    lv_obj_set_width(ui_Labeladd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeladd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labeladd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeladd, "+");

    ui_Buttonsub = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Buttonsub, 54);
    lv_obj_set_height(ui_Buttonsub, 50);
    lv_obj_set_x(ui_Buttonsub, 120);
    lv_obj_set_y(ui_Buttonsub, 64);
    lv_obj_set_align(ui_Buttonsub, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonsub, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonsub, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonsub, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonsub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelsub = lv_label_create(ui_Buttonsub);
    lv_obj_set_width(ui_Labelsub, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsub, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelsub, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsub, "-");

    ui_Buttonequal = lv_btn_create(ui_calculator);
    lv_obj_set_width(ui_Buttonequal, 54);
    lv_obj_set_height(ui_Buttonequal, 50);
    lv_obj_set_x(ui_Buttonequal, 120);
    lv_obj_set_y(ui_Buttonequal, 130);
    lv_obj_set_align(ui_Buttonequal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonequal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonequal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonequal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonequal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelequal = lv_label_create(ui_Buttonequal);
    lv_obj_set_width(ui_Labelequal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelequal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelequal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelequal, "=");

    ui_ioput = lv_textarea_create(ui_calculator);
    lv_obj_set_width(ui_ioput, 327);
    lv_obj_set_height(ui_ioput, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_ioput, 0);
    lv_obj_set_y(ui_ioput, -135);
    lv_obj_set_align(ui_ioput, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ioput, "calculate...");
    lv_textarea_set_one_line(ui_ioput, true);



    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button0, ui_event_Button0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonmul, ui_event_Buttonmul, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttondiv, ui_event_Buttondiv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttondel, ui_event_Buttondel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonadd, ui_event_Buttonadd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonsub, ui_event_Buttonsub, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonequal, ui_event_Buttonequal, LV_EVENT_ALL, NULL);

}
