// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CANNIBALSCREEN_H
#define UI_CANNIBALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_cannibalscreen
extern void ui_cannibalscreen_screen_init(void);
extern void ui_cannibalscreen_screen_destroy(void);
extern void ui_event_cannibalscreen(lv_event_t * e);
extern lv_obj_t * ui_cannibalscreen;
extern lv_obj_t * ui_background4;
extern void ui_event_Insectremoval4(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval4;
extern void ui_event_fertilize4(lv_event_t * e);
extern lv_obj_t * ui_fertilize4;
extern void ui_event_watering4(lv_event_t * e);
extern lv_obj_t * ui_watering4;
extern lv_obj_t * ui_health4;
extern void ui_event_healthlabel4(lv_event_t * e);
extern lv_obj_t * ui_healthlabel4;
extern lv_obj_t * ui_healthImage4;
extern lv_obj_t * ui_state4;
extern void ui_event_statelabel4(lv_event_t * e);
extern lv_obj_t * ui_statelabel4;
extern lv_obj_t * ui_stateImage4;
extern lv_obj_t * ui_humidity4;
extern void ui_event_humiditylabel4(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel4;
extern lv_obj_t * ui_humidityImage4;
extern lv_obj_t * ui_temperature4;
extern void ui_event_temperaturelabel4(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel4;
extern lv_obj_t * ui_temperatureImage4;
extern lv_obj_t * ui_light4;
extern void ui_event_lightlabel4(lv_event_t * e);
extern lv_obj_t * ui_lightlabel4;
extern lv_obj_t * ui_lightImage4;
extern lv_obj_t * ui_weather4;
extern void ui_event_weatherlabel4(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel4;
extern lv_obj_t * ui_weatherimage4;
extern lv_obj_t * ui_season4;
extern lv_obj_t * ui_seasonimage4;
extern void ui_event_seasonlabel4(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel4;
extern void ui_event_Illustrated4(lv_event_t * e);
extern lv_obj_t * ui_Illustrated4;
extern lv_obj_t * ui_next4;
extern lv_obj_t * ui_droplets4;
extern void ui_event_getseed4(lv_event_t * e);
extern lv_obj_t * ui_getseed4;
extern void ui_event_plantstagetextarea4(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea4;
extern void ui_event_plant4(lv_event_t * e);
extern lv_obj_t * ui_plant4;
extern lv_obj_t * ui_plantimg4;
extern lv_obj_t * ui_plantlabel4;
extern lv_obj_t * ui_achivevment4;
extern void ui_event_achivevmentimage4(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage4;
extern lv_obj_t * ui_achivevmentlabel4;
extern lv_obj_t * ui_growthstage3;
extern lv_obj_t * ui_growthstageimage4;
extern void ui_event_growthstagelabel4(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel4;
extern void ui_event_back3(lv_event_t * e);
extern lv_obj_t * ui_back3;
extern lv_obj_t * ui_Cannibal1;
extern void ui_event_Cannibal2(lv_event_t * e);
extern lv_obj_t * ui_Cannibal2;
extern void ui_event_Cannibal3(lv_event_t * e);
extern lv_obj_t * ui_Cannibal3;
extern void ui_event_Cannibal4(lv_event_t * e);
extern lv_obj_t * ui_Cannibal4;
extern void ui_event_Cannibal5(lv_event_t * e);
extern lv_obj_t * ui_Cannibal5;
extern void ui_event_Cannibal6(lv_event_t * e);
extern lv_obj_t * ui_Cannibal6;
extern void ui_event_Cannibal7(lv_event_t * e);
extern lv_obj_t * ui_Cannibal7;
extern lv_obj_t * ui_message4;
extern void ui_event_Label11(lv_event_t * e);
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

