// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CACTUSSCREEN_H
#define UI_CACTUSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_cactusscreen
extern void ui_cactusscreen_screen_init(void);
extern void ui_cactusscreen_screen_destroy(void);
extern lv_obj_t * ui_cactusscreen;
extern lv_obj_t * ui_background3;
extern void ui_event_Insectremoval3(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval3;
extern void ui_event_fertilize3(lv_event_t * e);
extern lv_obj_t * ui_fertilize3;
extern void ui_event_watering3(lv_event_t * e);
extern lv_obj_t * ui_watering3;
extern lv_obj_t * ui_health3;
extern void ui_event_healthlabel3(lv_event_t * e);
extern lv_obj_t * ui_healthlabel3;
extern lv_obj_t * ui_healthImage3;
extern lv_obj_t * ui_state3;
extern void ui_event_statelabel3(lv_event_t * e);
extern lv_obj_t * ui_statelabel3;
extern lv_obj_t * ui_stateImage3;
extern lv_obj_t * ui_humidity3;
extern void ui_event_humiditylabel3(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel3;
extern lv_obj_t * ui_humidityImage3;
extern lv_obj_t * ui_temperature3;
extern void ui_event_temperaturelabel3(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel3;
extern lv_obj_t * ui_temperatureImage3;
extern lv_obj_t * ui_light3;
extern void ui_event_lightlabel3(lv_event_t * e);
extern lv_obj_t * ui_lightlabel3;
extern lv_obj_t * ui_lightImage3;
extern lv_obj_t * ui_weather3;
extern void ui_event_weatherlabel3(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel3;
extern lv_obj_t * ui_weatherimage3;
extern lv_obj_t * ui_season3;
extern lv_obj_t * ui_seasonimage3;
extern void ui_event_seasonlabel3(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel3;
extern void ui_event_Illustrated3(lv_event_t * e);
extern lv_obj_t * ui_Illustrated3;
extern void ui_event_next3(lv_event_t * e);
extern lv_obj_t * ui_next3;
extern lv_obj_t * ui_droplets3;
extern void ui_event_getseed3(lv_event_t * e);
extern lv_obj_t * ui_getseed3;
extern void ui_event_plantstagetextarea3(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea3;
extern void ui_event_plant3(lv_event_t * e);
extern lv_obj_t * ui_plant3;
extern lv_obj_t * ui_plantimg3;
extern lv_obj_t * ui_plantlabel3;
extern lv_obj_t * ui_achivevment3;
extern void ui_event_achivevmentimage3(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage3;
extern lv_obj_t * ui_achivevmentlabel3;
extern lv_obj_t * ui_growthstage2;
extern lv_obj_t * ui_growthstageimage3;
extern void ui_event_growthstagelabel3(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel3;
extern void ui_event_back2(lv_event_t * e);
extern lv_obj_t * ui_back2;
extern lv_obj_t * ui_Cactus1;
extern void ui_event_Cactus2(lv_event_t * e);
extern lv_obj_t * ui_Cactus2;
extern void ui_event_Cactus3(lv_event_t * e);
extern lv_obj_t * ui_Cactus3;
extern void ui_event_Cactus4(lv_event_t * e);
extern lv_obj_t * ui_Cactus4;
extern void ui_event_Cactus5(lv_event_t * e);
extern lv_obj_t * ui_Cactus5;
extern void ui_event_Cactus6(lv_event_t * e);
extern lv_obj_t * ui_Cactus6;
extern void ui_event_Cactus7(lv_event_t * e);
extern lv_obj_t * ui_Cactus7;
extern lv_obj_t * ui_message3;
extern void ui_event_Label10(lv_event_t * e);
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

