// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_firstscreen_screen_init(void)
{
    ui_firstscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_firstscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_firstscreen, &ui_img_back1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_firstscreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Insectremoval1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_Insectremoval1, &ui_img_bug_spray_png);
    lv_obj_set_width(ui_Insectremoval1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Insectremoval1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Insectremoval1, -245);
    lv_obj_set_y(ui_Insectremoval1, 181);
    lv_obj_set_align(ui_Insectremoval1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Insectremoval1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Insectremoval1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Insectremoval1, 150);

    ui_fertilize1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_fertilize1, &ui_img_treefood_png);
    lv_obj_set_width(ui_fertilize1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fertilize1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fertilize1, -304);
    lv_obj_set_y(ui_fertilize1, 179);
    lv_obj_set_align(ui_fertilize1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fertilize1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fertilize1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_fertilize1, 150);

    ui_watering1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_watering1, &ui_img_wateringcan_png);
    lv_obj_set_width(ui_watering1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watering1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watering1, -365);
    lv_obj_set_y(ui_watering1, 176);
    lv_obj_set_align(ui_watering1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watering1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_watering1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_watering1, 180);

    ui_health1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_health1);
    lv_obj_set_width(ui_health1, 92);
    lv_obj_set_height(ui_health1, 39);
    lv_obj_set_x(ui_health1, -297);
    lv_obj_set_y(ui_health1, -2);
    lv_obj_set_align(ui_health1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_health1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_healthlabel1 = lv_label_create(ui_health1);
    lv_obj_set_width(ui_healthlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_healthlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_healthlabel1, 13);
    lv_obj_set_y(ui_healthlabel1, 10);
    lv_obj_set_align(ui_healthlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_healthlabel1, "健康 :");
    lv_obj_set_style_text_font(ui_healthlabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_healthImage1 = lv_img_create(ui_health1);
    lv_img_set_src(ui_healthImage1, &ui_img_561135566);
    lv_obj_set_width(ui_healthImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_healthImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_healthImage1, -27);
    lv_obj_set_y(ui_healthImage1, 1);
    lv_obj_set_align(ui_healthImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_healthImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_healthImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_healthImage1, 150);

    ui_state1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_state1);
    lv_obj_set_width(ui_state1, 114);
    lv_obj_set_height(ui_state1, 56);
    lv_obj_set_x(ui_state1, -303);
    lv_obj_set_y(ui_state1, 59);
    lv_obj_set_align(ui_state1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_state1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statelabel1 = lv_label_create(ui_state1);
    lv_obj_set_width(ui_statelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statelabel1, 22);
    lv_obj_set_y(ui_statelabel1, 5);
    lv_obj_set_align(ui_statelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statelabel1, "状态 :");
    lv_obj_set_style_text_font(ui_statelabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stateImage1 = lv_img_create(ui_state1);
    lv_img_set_src(ui_stateImage1, &ui_img_projectile_star_png);
    lv_obj_set_width(ui_stateImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateImage1, -20);
    lv_obj_set_y(ui_stateImage1, -3);
    lv_obj_set_align(ui_stateImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stateImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stateImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_stateImage1, 400);

    ui_humidity1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_humidity1);
    lv_obj_set_width(ui_humidity1, 80);
    lv_obj_set_height(ui_humidity1, 48);
    lv_obj_set_x(ui_humidity1, 251);
    lv_obj_set_y(ui_humidity1, -49);
    lv_obj_set_align(ui_humidity1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humidity1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humiditylabel1 = lv_label_create(ui_humidity1);
    lv_obj_set_width(ui_humiditylabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiditylabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiditylabel1, 23);
    lv_obj_set_y(ui_humiditylabel1, 8);
    lv_obj_set_align(ui_humiditylabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humiditylabel1, "湿度:");
    lv_obj_set_style_text_font(ui_humiditylabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityImage1 = lv_img_create(ui_humidity1);
    lv_img_set_src(ui_humidityImage1, &ui_img_waterdrop_png);
    lv_obj_set_width(ui_humidityImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidityImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidityImage1, -10);
    lv_obj_set_y(ui_humidityImage1, 2);
    lv_obj_set_align(ui_humidityImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidityImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humidityImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humidityImage1, 400);

    ui_temperature1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_temperature1);
    lv_obj_set_width(ui_temperature1, 76);
    lv_obj_set_height(ui_temperature1, 46);
    lv_obj_set_x(ui_temperature1, 251);
    lv_obj_set_y(ui_temperature1, 95);
    lv_obj_set_align(ui_temperature1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temperature1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperaturelabel1 = lv_label_create(ui_temperature1);
    lv_obj_set_width(ui_temperaturelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturelabel1, 23);
    lv_obj_set_y(ui_temperaturelabel1, 10);
    lv_obj_set_align(ui_temperaturelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperaturelabel1, "温度 :");
    lv_obj_set_style_text_font(ui_temperaturelabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureImage1 = lv_img_create(ui_temperature1);
    lv_img_set_src(ui_temperatureImage1, &ui_img_1795366294);
    lv_obj_set_width(ui_temperatureImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatureImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureImage1, -11);
    lv_obj_set_y(ui_temperatureImage1, 1);
    lv_obj_set_align(ui_temperatureImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temperatureImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperatureImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temperatureImage1, 180);

    ui_light1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_light1);
    lv_obj_set_width(ui_light1, 92);
    lv_obj_set_height(ui_light1, 53);
    lv_obj_set_x(ui_light1, 254);
    lv_obj_set_y(ui_light1, 25);
    lv_obj_set_align(ui_light1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_light1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lightlabel1 = lv_label_create(ui_light1);
    lv_obj_set_width(ui_lightlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightlabel1, 24);
    lv_obj_set_y(ui_lightlabel1, 9);
    lv_obj_set_align(ui_lightlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightlabel1, "光照:");
    lv_obj_set_style_text_font(ui_lightlabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightImage1 = lv_img_create(ui_light1);
    lv_img_set_src(ui_lightImage1, &ui_img_1138793207);
    lv_obj_set_width(ui_lightImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightImage1, -15);
    lv_obj_set_y(ui_lightImage1, 0);
    lv_obj_set_align(ui_lightImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lightImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lightImage1, 170);

    ui_weather1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_weather1);
    lv_obj_set_width(ui_weather1, 82);
    lv_obj_set_height(ui_weather1, 45);
    lv_obj_set_x(ui_weather1, -170);
    lv_obj_set_y(ui_weather1, -210);
    lv_obj_set_align(ui_weather1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label1 = lv_label_create(ui_weather1);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label1, 19);
    lv_obj_set_y(ui_label1, 3);
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "天气");
    lv_obj_set_style_text_font(ui_label1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image1 = lv_img_create(ui_weather1);
    lv_img_set_src(ui_image1, &ui_img_1606731336);
    lv_obj_set_width(ui_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image1, -14);
    lv_obj_set_y(ui_image1, 2);
    lv_obj_set_align(ui_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_image1, 160);

    ui_season1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_season1);
    lv_obj_set_width(ui_season1, 67);
    lv_obj_set_height(ui_season1, 39);
    lv_obj_set_x(ui_season1, 75);
    lv_obj_set_y(ui_season1, -210);
    lv_obj_set_align(ui_season1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_season1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seasonimage1 = lv_img_create(ui_season1);
    lv_img_set_src(ui_seasonimage1, &ui_img_683165229);
    lv_obj_set_width(ui_seasonimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seasonimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seasonimage1, -16);
    lv_obj_set_y(ui_seasonimage1, 2);
    lv_obj_set_align(ui_seasonimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seasonimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seasonimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seasonimage1, 120);

    ui_seasonlabel1 = lv_label_create(ui_season1);
    lv_obj_set_width(ui_seasonlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seasonlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seasonlabel1, 14);
    lv_obj_set_y(ui_seasonlabel1, 3);
    lv_obj_set_align(ui_seasonlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_seasonlabel1, "春天");
    lv_obj_set_style_text_font(ui_seasonlabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firstplant = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_firstplant);
    lv_obj_set_width(ui_firstplant, 456);
    lv_obj_set_height(ui_firstplant, 237);
    lv_obj_set_x(ui_firstplant, 49);
    lv_obj_set_y(ui_firstplant, 300);
    lv_obj_set_align(ui_firstplant, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_firstplant, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Illustrated1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_Illustrated1, &ui_img_178160675);
    lv_obj_set_width(ui_Illustrated1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Illustrated1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Illustrated1, 292);
    lv_obj_set_y(ui_Illustrated1, 180);
    lv_obj_set_align(ui_Illustrated1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Illustrated1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Illustrated1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Illustrated1, 240);

    ui_next1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_next1, &ui_img_zen_nextgarden_png);
    lv_obj_set_width(ui_next1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_next1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_next1, 360);
    lv_obj_set_y(ui_next1, 184);
    lv_obj_set_align(ui_next1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_next1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_next1, 200);

    ui_droplets1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_droplets1, &ui_img_354690767);
    lv_obj_set_width(ui_droplets1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_droplets1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_droplets1, 82);
    lv_obj_set_y(ui_droplets1, 7);
    lv_obj_set_align(ui_droplets1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droplets1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_droplets1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_droplets1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseed1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_getseed1, &ui_img_876520695);
    lv_obj_set_width(ui_getseed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseed1, 237);
    lv_obj_set_y(ui_getseed1, 177);
    lv_obj_set_align(ui_getseed1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_getseed1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_getseed1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_getplanttextarea1 = lv_textarea_create(ui_firstscreen);
    lv_obj_set_width(ui_getplanttextarea1, 184);
    lv_obj_set_height(ui_getplanttextarea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_getplanttextarea1, -12);
    lv_obj_set_y(ui_getplanttextarea1, -72);
    lv_obj_set_align(ui_getplanttextarea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_getplanttextarea1, "获得");
    lv_textarea_set_placeholder_text(ui_getplanttextarea1, "Placeholder...");
    lv_textarea_set_one_line(ui_getplanttextarea1, true);
    lv_obj_set_style_text_font(ui_getplanttextarea1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_getplanttextarea1, lv_color_hex(0xB7C16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_getplanttextarea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_getplanttextarea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_getplanttextarea1, LV_BLEND_MODE_NORMAL, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_getplanttextarea1, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_plant1 = lv_obj_create(ui_firstscreen);
    lv_obj_remove_style_all(ui_plant1);
    lv_obj_set_width(ui_plant1, 86);
    lv_obj_set_height(ui_plant1, 47);
    lv_obj_set_x(ui_plant1, -301);
    lv_obj_set_y(ui_plant1, -52);
    lv_obj_set_align(ui_plant1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_plant1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantimg1 = lv_img_create(ui_plant1);
    lv_img_set_src(ui_plantimg1, &ui_img_1745983305);
    lv_obj_set_width(ui_plantimg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plantimg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plantimg1, -22);
    lv_obj_set_y(ui_plantimg1, -6);
    lv_obj_set_align(ui_plantimg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_plantimg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_plantimg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantlabel1 = lv_label_create(ui_plant1);
    lv_obj_set_width(ui_plantlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plantlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plantlabel1, 17);
    lv_obj_set_y(ui_plantlabel1, 3);
    lv_obj_set_align(ui_plantlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plantlabel1, "种植");
    lv_obj_set_style_text_font(ui_plantlabel1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seed = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_seed, &ui_img_577302902);
    lv_obj_set_width(ui_seed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seed, -237);
    lv_obj_set_y(ui_seed, -48);
    lv_obj_set_align(ui_seed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seed, 128);
    lv_obj_set_style_opa(ui_seed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seed1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_seed1, &ui_img_seed1_png);
    lv_obj_set_width(ui_seed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seed1, -10);
    lv_obj_set_y(ui_seed1, 144);
    lv_obj_set_align(ui_seed1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seed1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seed1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seed1, 10);

    ui_sprout1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_sprout1, &ui_img_sprout1_png);
    lv_obj_set_width(ui_sprout1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sprout1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sprout1, -6);
    lv_obj_set_y(ui_sprout1, 117);
    lv_obj_set_align(ui_sprout1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sprout1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sprout1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sprout1, 20);

    ui_seeding1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_seeding1, &ui_img_seedling1_png);
    lv_obj_set_width(ui_seeding1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seeding1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seeding1, -10);
    lv_obj_set_y(ui_seeding1, 111);
    lv_obj_set_align(ui_seeding1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seeding1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seeding1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seeding1, 30);

    ui_mature1 = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_mature1, &ui_img_mature1_png);
    lv_obj_set_width(ui_mature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mature1, -8);
    lv_obj_set_y(ui_mature1, 94);
    lv_obj_set_align(ui_mature1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mature1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mature1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_mature1, 40);

    ui_flowering = lv_img_create(ui_firstscreen);
    lv_img_set_src(ui_flowering, &ui_img_flowering1_png);
    lv_obj_set_width(ui_flowering, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_flowering, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_flowering, -4);
    lv_obj_set_y(ui_flowering, 69);
    lv_obj_set_align(ui_flowering, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flowering, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flowering, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_flowering, 60);

    lv_obj_add_event_cb(ui_Insectremoval1, ui_event_Insectremoval1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fertilize1, ui_event_fertilize1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watering1, ui_event_watering1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Illustrated1, ui_event_Illustrated1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next1, ui_event_next1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_getseed1, ui_event_getseed1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plant1, ui_event_plant1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seeding1, ui_event_seeding1, LV_EVENT_ALL, NULL);

}
