// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ILLUSTRATEDSCREEN_H
#define UI_ILLUSTRATEDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_IllustratedScreen
extern void ui_IllustratedScreen_screen_init(void);
extern void ui_IllustratedScreen_screen_destroy(void);
extern lv_obj_t * ui_IllustratedScreen;
extern lv_obj_t * ui_illustratedbg;
extern lv_obj_t * ui_illuTextArea;
extern lv_obj_t * ui_illuImage;
extern void ui_event_back(lv_event_t * e);
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_illplant;
extern void ui_event_sunflower(lv_event_t * e);
extern lv_obj_t * ui_sunflower;
extern void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

