// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_INITSCREEN_H
#define UI_INITSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_initscreen
extern void ui_initscreen_screen_init(void);
extern void ui_initscreen_screen_destroy(void);
extern lv_obj_t * ui_initscreen;
extern lv_obj_t * ui_Label1;
extern void ui_event_getseedinit(lv_event_t * e);
extern lv_obj_t * ui_getseedinit;
extern lv_obj_t * ui_getseedlabelinit;
extern lv_obj_t * ui_getseedimginit;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

