// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_initscreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_getseedinit = NULL;
lv_obj_t * ui_getseedlabelinit = NULL;
lv_obj_t * ui_getseedimginit = NULL;
// event funtions
void ui_event_getseedinit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Opacityfull1_Animation(ui_Label1, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_sunflowerscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000, &ui_sunflowerscreen_screen_init);
    }
}

// build funtions

void ui_initscreen_screen_init(void)
{
    ui_initscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_initscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_initscreen, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_initscreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_initscreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, 30);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "恭喜获得一株向日葵\\^o^/\\^o^/\\^o^/");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseedinit = lv_obj_create(ui_initscreen);
    lv_obj_remove_style_all(ui_getseedinit);
    lv_obj_set_width(ui_getseedinit, 285);
    lv_obj_set_height(ui_getseedinit, 133);
    lv_obj_set_x(ui_getseedinit, -4);
    lv_obj_set_y(ui_getseedinit, -3);
    lv_obj_set_align(ui_getseedinit, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_getseedinit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_getseedlabelinit = lv_label_create(ui_getseedinit);
    lv_obj_set_width(ui_getseedlabelinit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseedlabelinit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseedlabelinit, 7);
    lv_obj_set_y(ui_getseedlabelinit, 32);
    lv_obj_set_align(ui_getseedlabelinit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_getseedlabelinit, "点击它获取你的第一株植物");
    lv_obj_set_style_text_font(ui_getseedlabelinit, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseedimginit = lv_img_create(ui_getseedinit);
    lv_img_set_src(ui_getseedimginit, &ui_img_876520695);
    lv_obj_set_width(ui_getseedimginit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseedimginit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseedimginit, -3);
    lv_obj_set_y(ui_getseedimginit, -5);
    lv_obj_set_align(ui_getseedimginit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_getseedimginit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_getseedimginit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_getseedinit, ui_event_getseedinit, LV_EVENT_ALL, NULL);

}

void ui_initscreen_screen_destroy(void)
{
    if(ui_initscreen) lv_obj_del(ui_initscreen);

    // NULL screen variables
    ui_initscreen = NULL;
    ui_Label1 = NULL;
    ui_getseedinit = NULL;
    ui_getseedlabelinit = NULL;
    ui_getseedimginit = NULL;

}
