// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_IllustratedScreen2_screen_init(void)
{
    ui_IllustratedScreen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IllustratedScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_illustratedbg2 = lv_img_create(ui_IllustratedScreen2);
    lv_img_set_src(ui_illustratedbg2, &ui_img_letterbg__png);
    lv_obj_set_width(ui_illustratedbg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_illustratedbg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_illustratedbg2, -10);
    lv_obj_set_y(ui_illustratedbg2, 14);
    lv_obj_set_align(ui_illustratedbg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_illustratedbg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_illustratedbg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_illustratedbg2, 600);

    ui_illuTextArea2 = lv_textarea_create(ui_IllustratedScreen2);
    lv_obj_set_width(ui_illuTextArea2, 467);
    lv_obj_set_height(ui_illuTextArea2, 318);
    lv_obj_set_x(ui_illuTextArea2, 84);
    lv_obj_set_y(ui_illuTextArea2, 55);
    lv_obj_set_align(ui_illuTextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_illuTextArea2, "Placeholder...");
    lv_obj_set_style_bg_color(ui_illuTextArea2, lv_color_hex(0xFFE2AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_illuTextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_illuImage2 = lv_img_create(ui_IllustratedScreen2);
    lv_img_set_src(ui_illuImage2, &ui_img_uppercaveplants__png);
    lv_obj_set_width(ui_illuImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_illuImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_illuImage2, -27);
    lv_obj_set_y(ui_illuImage2, -212);
    lv_obj_set_align(ui_illuImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_illuImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_illuImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_illuImage2, 120);

}
