// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_initscreen_screen_init(void)
{
    ui_initscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_initscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_initscreen, &ui_img_back1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_initscreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_initscreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -9);
    lv_obj_set_y(ui_Label1, 46);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "恭喜获得一株向日葵\\^o^/\\^o^/\\^o^/");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseedinit = lv_obj_create(ui_initscreen);
    lv_obj_remove_style_all(ui_getseedinit);
    lv_obj_set_width(ui_getseedinit, 211);
    lv_obj_set_height(ui_getseedinit, 87);
    lv_obj_set_x(ui_getseedinit, -11);
    lv_obj_set_y(ui_getseedinit, -57);
    lv_obj_set_align(ui_getseedinit, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_getseedinit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_getseedlabelinit = lv_label_create(ui_getseedinit);
    lv_obj_set_width(ui_getseedlabelinit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseedlabelinit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseedlabelinit, 3);
    lv_obj_set_y(ui_getseedlabelinit, 34);
    lv_obj_set_align(ui_getseedlabelinit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_getseedlabelinit, "点击它,获取你的第一株植物!!");
    lv_obj_set_style_text_font(ui_getseedlabelinit, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseedimginit = lv_img_create(ui_getseedinit);
    lv_img_set_src(ui_getseedimginit, &ui_img_876520695);
    lv_obj_set_width(ui_getseedimginit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseedimginit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseedimginit, -3);
    lv_obj_set_y(ui_getseedimginit, -5);
    lv_obj_set_align(ui_getseedimginit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_getseedimginit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_getseedimginit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_getseedinit, ui_event_getseedinit, LV_EVENT_ALL, NULL);

}
