// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_IllustratedScreen1_screen_init(void)
{
    ui_IllustratedScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IllustratedScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_illustratedbg1 = lv_img_create(ui_IllustratedScreen1);
    lv_img_set_src(ui_illustratedbg1, &ui_img_letterbg__png);
    lv_obj_set_width(ui_illustratedbg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_illustratedbg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_illustratedbg1, -4);
    lv_obj_set_y(ui_illustratedbg1, 5);
    lv_obj_set_align(ui_illustratedbg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_illustratedbg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_illustratedbg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_illustratedbg1, 600);

    ui_illuTextArea1 = lv_textarea_create(ui_IllustratedScreen1);
    lv_obj_set_width(ui_illuTextArea1, 467);
    lv_obj_set_height(ui_illuTextArea1, 318);
    lv_obj_set_x(ui_illuTextArea1, 67);
    lv_obj_set_y(ui_illuTextArea1, 25);
    lv_obj_set_align(ui_illuTextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_illuTextArea1, "Placeholder...");
    lv_obj_set_style_bg_color(ui_illuTextArea1, lv_color_hex(0xFFE2AF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_illuTextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_illuImage1 = lv_img_create(ui_IllustratedScreen1);
    lv_img_set_src(ui_illuImage1, &ui_img_uppercaveplants__png);
    lv_obj_set_width(ui_illuImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_illuImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_illuImage1, -27);
    lv_obj_set_y(ui_illuImage1, -212);
    lv_obj_set_align(ui_illuImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_illuImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_illuImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_illuImage1, 120);

    ui_sunflower = lv_img_create(ui_IllustratedScreen1);
    lv_img_set_src(ui_sunflower, &ui_img_sunflower_png);
    lv_obj_set_width(ui_sunflower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower, -263);
    lv_obj_set_y(ui_sunflower, -66);
    lv_obj_set_align(ui_sunflower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sunflower, 80);

    ui_Label2 = lv_label_create(ui_IllustratedScreen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -265);
    lv_obj_set_y(ui_Label2, 66);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "向日葵");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_FontPlant, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_IllustratedScreen1);
    lv_img_set_src(ui_Image17, &ui_img_zen_prevgarden_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, -345);
    lv_obj_set_y(ui_Image17, -179);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, NULL);

}
