// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_sunflowerscreen = NULL;
lv_obj_t * ui_background = NULL;
lv_obj_t * ui_Insectremoval1 = NULL;
lv_obj_t * ui_fertilize1 = NULL;
lv_obj_t * ui_watering1 = NULL;
lv_obj_t * ui_health1 = NULL;
lv_obj_t * ui_healthlabel1 = NULL;
lv_obj_t * ui_healthImage1 = NULL;
lv_obj_t * ui_state1 = NULL;
lv_obj_t * ui_statelabel1 = NULL;
lv_obj_t * ui_stateImage1 = NULL;
lv_obj_t * ui_humidity1 = NULL;
lv_obj_t * ui_humiditylabel1 = NULL;
lv_obj_t * ui_humidityImage1 = NULL;
lv_obj_t * ui_temperature1 = NULL;
lv_obj_t * ui_temperaturelabel1 = NULL;
lv_obj_t * ui_temperatureImage1 = NULL;
lv_obj_t * ui_light1 = NULL;
lv_obj_t * ui_lightlabel1 = NULL;
lv_obj_t * ui_lightImage1 = NULL;
lv_obj_t * ui_weather1 = NULL;
lv_obj_t * ui_weatherlabel1 = NULL;
lv_obj_t * ui_weatherimage1 = NULL;
lv_obj_t * ui_season1 = NULL;
lv_obj_t * ui_seasonimage1 = NULL;
lv_obj_t * ui_seasonlabel1 = NULL;
lv_obj_t * ui_Illustrated1 = NULL;
lv_obj_t * ui_next1 = NULL;
lv_obj_t * ui_droplets1 = NULL;
lv_obj_t * ui_getseed1 = NULL;
lv_obj_t * ui_plantstagetextarea1 = NULL;
lv_obj_t * ui_plant1 = NULL;
lv_obj_t * ui_plantimg1 = NULL;
lv_obj_t * ui_plantlabel1 = NULL;
lv_obj_t * ui_achivevment1 = NULL;
lv_obj_t * ui_achivevmentimage1 = NULL;
lv_obj_t * ui_achivevmentlabel1 = NULL;
lv_obj_t * ui_growthstage = NULL;
lv_obj_t * ui_growthstageimage1 = NULL;
lv_obj_t * ui_growthstagelabel1 = NULL;
lv_obj_t * ui_sunflower1 = NULL;
lv_obj_t * ui_sunflower2 = NULL;
lv_obj_t * ui_sunflower3 = NULL;
lv_obj_t * ui_sunflower4 = NULL;
lv_obj_t * ui_sunflower5 = NULL;
lv_obj_t * ui_sunflower6 = NULL;
lv_obj_t * ui_sunflower7 = NULL;
lv_obj_t * ui_message = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_backhome = NULL;
// event funtions
void ui_event_Insectremoval1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Insectremovalmove1_Animation(ui_Insectremoval1, 0);
        Insectremovalback1_Animation(ui_Insectremoval1, 2000);
        plant_insert_removal(e);
    }
}

void ui_event_fertilize1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fertilizemove1_Animation(ui_fertilize1, 0);
        fertilizeback1_Animation(ui_fertilize1, 3000);
        imageangle1_Animation(ui_fertilize1, 1000);
        plant_fertilize(e);
    }
}

void ui_event_watering1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wateringmove1_Animation(ui_watering1, 0);
        imageangle1_Animation(ui_watering1, 1000);
        Opacityfull1_Animation(ui_droplets1, 1000);
        wateringback1_Animation(ui_watering1, 3000);
        Opacityzero1_Animation(ui_droplets1, 1000);
        plant_watering(e);
    }
}

void ui_event_healthlabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        healthchange(e);
    }
}

void ui_event_statelabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        agechange(e);
    }
}

void ui_event_humiditylabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        humiditychange(e);
    }
}

void ui_event_temperaturelabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        temperaturechange(e);
    }
}

void ui_event_lightlabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lightchange(e);
    }
}

void ui_event_weatherlabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        weatherchange(e);
    }
}

void ui_event_seasonlabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        seasonchange(e);
    }
}

void ui_event_Illustrated1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IllustratedScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_IllustratedScreen_screen_init);
        switch2illustratedscreen(e);
    }
}

void ui_event_next1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_tomatoscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_tomatoscreen_screen_init);
    }
}

void ui_event_getseed1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_storeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_storeScreen_screen_init);
    }
}

void ui_event_plantstagetextarea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        message_plantstage(e);
    }
}

void ui_event_plant1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflowerseed(e);
    }
}

void ui_event_achivevmentimage1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_storeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_storeScreen_screen_init);
    }
}

void ui_event_growthstagelabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        growthstagechange(e);
    }
}

void ui_event_sunflower2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflower2(e);
    }
}

void ui_event_sunflower3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflower3(e);
    }
}

void ui_event_sunflower4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflower4(e);
    }
}

void ui_event_sunflower5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflower5(e);
    }
}

void ui_event_sunflower6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflower6(e);
    }
}

void ui_event_sunflower7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_sunflower7(e);
    }
}

void ui_event_Label4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_message(e);
    }
}

void ui_event_backhome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
    }
}

// build funtions

void ui_sunflowerscreen_screen_init(void)
{
    ui_sunflowerscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sunflowerscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_sunflowerscreen, &ui_img_cloudy_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_sunflowerscreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_background = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_background, &ui_img_inventory_png);
    lv_obj_set_width(ui_background, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_background, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_background, 2);
    lv_obj_set_y(ui_background, 14);
    lv_obj_set_align(ui_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Insectremoval1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_Insectremoval1, &ui_img_bug_spray_png);
    lv_obj_set_width(ui_Insectremoval1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Insectremoval1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Insectremoval1, -236);
    lv_obj_set_y(ui_Insectremoval1, 180);
    lv_obj_set_align(ui_Insectremoval1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Insectremoval1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Insectremoval1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Insectremoval1, 150);

    ui_fertilize1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_fertilize1, &ui_img_treefood_png);
    lv_obj_set_width(ui_fertilize1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fertilize1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fertilize1, -303);
    lv_obj_set_y(ui_fertilize1, 180);
    lv_obj_set_align(ui_fertilize1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fertilize1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fertilize1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_fertilize1, 150);

    ui_watering1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_watering1, &ui_img_wateringcan_png);
    lv_obj_set_width(ui_watering1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watering1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watering1, -371);
    lv_obj_set_y(ui_watering1, 176);
    lv_obj_set_align(ui_watering1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watering1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_watering1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_watering1, 180);

    ui_health1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_health1);
    lv_obj_set_width(ui_health1, 281);
    lv_obj_set_height(ui_health1, 45);
    lv_obj_set_x(ui_health1, -250);
    lv_obj_set_y(ui_health1, 0);
    lv_obj_set_align(ui_health1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_health1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_healthlabel1 = lv_label_create(ui_health1);
    lv_obj_set_width(ui_healthlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_healthlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_healthlabel1, -28);
    lv_obj_set_y(ui_healthlabel1, 7);
    lv_obj_set_align(ui_healthlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_healthlabel1, "健康");
    lv_obj_set_style_text_font(ui_healthlabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_healthImage1 = lv_img_create(ui_health1);
    lv_img_set_src(ui_healthImage1, &ui_img_561135566);
    lv_obj_set_width(ui_healthImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_healthImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_healthImage1, -93);
    lv_obj_set_y(ui_healthImage1, -1);
    lv_obj_set_align(ui_healthImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_healthImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_healthImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_healthImage1, 150);

    ui_state1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_state1);
    lv_obj_set_width(ui_state1, 229);
    lv_obj_set_height(ui_state1, 56);
    lv_obj_set_x(ui_state1, -283);
    lv_obj_set_y(ui_state1, 59);
    lv_obj_set_align(ui_state1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_state1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statelabel1 = lv_label_create(ui_state1);
    lv_obj_set_width(ui_statelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statelabel1, 6);
    lv_obj_set_y(ui_statelabel1, 5);
    lv_obj_set_align(ui_statelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statelabel1, "年龄");
    lv_obj_set_style_text_font(ui_statelabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stateImage1 = lv_img_create(ui_state1);
    lv_img_set_src(ui_stateImage1, &ui_img_projectile_star_png);
    lv_obj_set_width(ui_stateImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateImage1, -59);
    lv_obj_set_y(ui_stateImage1, -2);
    lv_obj_set_align(ui_stateImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stateImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stateImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_stateImage1, 400);

    ui_humidity1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_humidity1);
    lv_obj_set_width(ui_humidity1, 207);
    lv_obj_set_height(ui_humidity1, 48);
    lv_obj_set_x(ui_humidity1, 292);
    lv_obj_set_y(ui_humidity1, -60);
    lv_obj_set_align(ui_humidity1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humidity1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humiditylabel1 = lv_label_create(ui_humidity1);
    lv_obj_set_width(ui_humiditylabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiditylabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiditylabel1, -15);
    lv_obj_set_y(ui_humiditylabel1, 9);
    lv_obj_set_align(ui_humiditylabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humiditylabel1, "湿度");
    lv_obj_set_style_text_font(ui_humiditylabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityImage1 = lv_img_create(ui_humidity1);
    lv_img_set_src(ui_humidityImage1, &ui_img_waterdrop_png);
    lv_obj_set_width(ui_humidityImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidityImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidityImage1, -76);
    lv_obj_set_y(ui_humidityImage1, 0);
    lv_obj_set_align(ui_humidityImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidityImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humidityImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humidityImage1, 400);

    ui_temperature1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_temperature1);
    lv_obj_set_width(ui_temperature1, 204);
    lv_obj_set_height(ui_temperature1, 46);
    lv_obj_set_x(ui_temperature1, 294);
    lv_obj_set_y(ui_temperature1, 57);
    lv_obj_set_align(ui_temperature1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temperature1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperaturelabel1 = lv_label_create(ui_temperature1);
    lv_obj_set_width(ui_temperaturelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturelabel1, -16);
    lv_obj_set_y(ui_temperaturelabel1, 7);
    lv_obj_set_align(ui_temperaturelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperaturelabel1, "温度");
    lv_obj_set_style_text_font(ui_temperaturelabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureImage1 = lv_img_create(ui_temperature1);
    lv_img_set_src(ui_temperatureImage1, &ui_img_1795366294);
    lv_obj_set_width(ui_temperatureImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatureImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureImage1, -77);
    lv_obj_set_y(ui_temperatureImage1, -3);
    lv_obj_set_align(ui_temperatureImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temperatureImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperatureImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temperatureImage1, 180);

    ui_light1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_light1);
    lv_obj_set_width(ui_light1, 210);
    lv_obj_set_height(ui_light1, 53);
    lv_obj_set_x(ui_light1, 292);
    lv_obj_set_y(ui_light1, -2);
    lv_obj_set_align(ui_light1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_light1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lightlabel1 = lv_label_create(ui_light1);
    lv_obj_set_width(ui_lightlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightlabel1, -14);
    lv_obj_set_y(ui_lightlabel1, 6);
    lv_obj_set_align(ui_lightlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightlabel1, "光照");
    lv_obj_set_style_text_font(ui_lightlabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightImage1 = lv_img_create(ui_light1);
    lv_img_set_src(ui_lightImage1, &ui_img_1138793207);
    lv_obj_set_width(ui_lightImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightImage1, -74);
    lv_obj_set_y(ui_lightImage1, -2);
    lv_obj_set_align(ui_lightImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lightImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lightImage1, 170);

    ui_weather1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_weather1);
    lv_obj_set_width(ui_weather1, 167);
    lv_obj_set_height(ui_weather1, 64);
    lv_obj_set_x(ui_weather1, -134);
    lv_obj_set_y(ui_weather1, -199);
    lv_obj_set_align(ui_weather1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherlabel1 = lv_label_create(ui_weather1);
    lv_obj_set_width(ui_weatherlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherlabel1, 8);
    lv_obj_set_y(ui_weatherlabel1, 1);
    lv_obj_set_align(ui_weatherlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherlabel1, "天气");
    lv_obj_set_style_text_font(ui_weatherlabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherimage1 = lv_img_create(ui_weather1);
    lv_img_set_src(ui_weatherimage1, &ui_img_1606731336);
    lv_obj_set_width(ui_weatherimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherimage1, -37);
    lv_obj_set_y(ui_weatherimage1, -5);
    lv_obj_set_align(ui_weatherimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weatherimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_season1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_season1);
    lv_obj_set_width(ui_season1, 134);
    lv_obj_set_height(ui_season1, 63);
    lv_obj_set_x(ui_season1, 15);
    lv_obj_set_y(ui_season1, -204);
    lv_obj_set_align(ui_season1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_season1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seasonimage1 = lv_img_create(ui_season1);
    lv_img_set_src(ui_seasonimage1, &ui_img_683165229);
    lv_obj_set_width(ui_seasonimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seasonimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seasonimage1, -27);
    lv_obj_set_y(ui_seasonimage1, -1);
    lv_obj_set_align(ui_seasonimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seasonimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seasonimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seasonimage1, 220);

    ui_seasonlabel1 = lv_label_create(ui_season1);
    lv_obj_set_width(ui_seasonlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seasonlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seasonlabel1, 29);
    lv_obj_set_y(ui_seasonlabel1, 7);
    lv_obj_set_align(ui_seasonlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_seasonlabel1, "春天");
    lv_obj_set_style_text_font(ui_seasonlabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Illustrated1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_Illustrated1, &ui_img_178160675);
    lv_obj_set_width(ui_Illustrated1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Illustrated1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Illustrated1, 316);
    lv_obj_set_y(ui_Illustrated1, 176);
    lv_obj_set_align(ui_Illustrated1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Illustrated1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Illustrated1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Illustrated1, 240);

    ui_next1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_next1, &ui_img_zen_nextgarden_png);
    lv_obj_set_width(ui_next1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_next1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_next1, 374);
    lv_obj_set_y(ui_next1, 183);
    lv_obj_set_align(ui_next1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_next1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_next1, 200);

    ui_droplets1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_droplets1, &ui_img_354690767);
    lv_obj_set_width(ui_droplets1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_droplets1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_droplets1, 82);
    lv_obj_set_y(ui_droplets1, 7);
    lv_obj_set_align(ui_droplets1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droplets1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_droplets1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_droplets1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseed1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_getseed1, &ui_img_876520695);
    lv_obj_set_width(ui_getseed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseed1, 264);
    lv_obj_set_y(ui_getseed1, 179);
    lv_obj_set_align(ui_getseed1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_getseed1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_getseed1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantstagetextarea1 = lv_textarea_create(ui_sunflowerscreen);
    lv_obj_set_width(ui_plantstagetextarea1, 184);
    lv_obj_set_height(ui_plantstagetextarea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_plantstagetextarea1, -22);
    lv_obj_set_y(ui_plantstagetextarea1, -79);
    lv_obj_set_align(ui_plantstagetextarea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_plantstagetextarea1, "Placeholder...");
    lv_textarea_set_one_line(ui_plantstagetextarea1, true);
    lv_obj_add_flag(ui_plantstagetextarea1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_plantstagetextarea1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_plantstagetextarea1, lv_color_hex(0xB7C16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_plantstagetextarea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_plantstagetextarea1, LV_BLEND_MODE_NORMAL, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_plantstagetextarea1, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_plantstagetextarea1, &ui_font_Font1, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_plant1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_plant1);
    lv_obj_set_width(ui_plant1, 87);
    lv_obj_set_height(ui_plant1, 45);
    lv_obj_set_x(ui_plant1, -343);
    lv_obj_set_y(ui_plant1, -207);
    lv_obj_set_align(ui_plant1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_plant1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantimg1 = lv_img_create(ui_plant1);
    lv_img_set_src(ui_plantimg1, &ui_img_1745983305);
    lv_obj_set_width(ui_plantimg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plantimg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plantimg1, -22);
    lv_obj_set_y(ui_plantimg1, -6);
    lv_obj_set_align(ui_plantimg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_plantimg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_plantimg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantlabel1 = lv_label_create(ui_plant1);
    lv_obj_set_width(ui_plantlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plantlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plantlabel1, 17);
    lv_obj_set_y(ui_plantlabel1, 3);
    lv_obj_set_align(ui_plantlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plantlabel1, "种植");
    lv_obj_set_style_text_font(ui_plantlabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_achivevment1 = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_achivevment1);
    lv_obj_set_width(ui_achivevment1, 84);
    lv_obj_set_height(ui_achivevment1, 77);
    lv_obj_set_x(ui_achivevment1, 346);
    lv_obj_set_y(ui_achivevment1, -133);
    lv_obj_set_align(ui_achivevment1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_achivevment1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_achivevmentimage1 = lv_img_create(ui_achivevment1);
    lv_img_set_src(ui_achivevmentimage1, &ui_img_403432398);
    lv_obj_set_width(ui_achivevmentimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_achivevmentimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_achivevmentimage1, -4);
    lv_obj_set_y(ui_achivevmentimage1, -10);
    lv_obj_set_align(ui_achivevmentimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_achivevmentimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_achivevmentimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_achivevmentlabel1 = lv_label_create(ui_achivevment1);
    lv_obj_set_width(ui_achivevmentlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_achivevmentlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_achivevmentlabel1, -4);
    lv_obj_set_y(ui_achivevmentlabel1, 23);
    lv_obj_set_align(ui_achivevmentlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_achivevmentlabel1, "成就");
    lv_obj_set_style_text_font(ui_achivevmentlabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_growthstage = lv_obj_create(ui_sunflowerscreen);
    lv_obj_remove_style_all(ui_growthstage);
    lv_obj_set_width(ui_growthstage, 197);
    lv_obj_set_height(ui_growthstage, 89);
    lv_obj_set_x(ui_growthstage, -295);
    lv_obj_set_y(ui_growthstage, -58);
    lv_obj_set_align(ui_growthstage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_growthstage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_growthstageimage1 = lv_img_create(ui_growthstage);
    lv_img_set_src(ui_growthstageimage1, &ui_img_577302902);
    lv_obj_set_width(ui_growthstageimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_growthstageimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_growthstageimage1, -45);
    lv_obj_set_y(ui_growthstageimage1, -1);
    lv_obj_set_align(ui_growthstageimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_growthstageimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_growthstageimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_growthstagelabel1 = lv_label_create(ui_growthstage);
    lv_obj_set_width(ui_growthstagelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_growthstagelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_growthstagelabel1, 19);
    lv_obj_set_y(ui_growthstagelabel1, 7);
    lv_obj_set_align(ui_growthstagelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_growthstagelabel1, "种子");
    lv_obj_set_style_text_font(ui_growthstagelabel1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sunflower1 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower1, &ui_img_sunflower1_png);
    lv_obj_set_width(ui_sunflower1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower1, -9);
    lv_obj_set_y(ui_sunflower1, 150);
    lv_obj_set_align(ui_sunflower1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sunflower1, 50);

    ui_sunflower2 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower2, &ui_img_sunflower2_png);
    lv_obj_set_width(ui_sunflower2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower2, -7);
    lv_obj_set_y(ui_sunflower2, 139);
    lv_obj_set_align(ui_sunflower2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sunflower2, 128);

    ui_sunflower3 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower3, &ui_img_sunflower3_png);
    lv_obj_set_width(ui_sunflower3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower3, 5);
    lv_obj_set_y(ui_sunflower3, 126);
    lv_obj_set_align(ui_sunflower3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sunflower3, 100);

    ui_sunflower4 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower4, &ui_img_sunflower4_png);
    lv_obj_set_width(ui_sunflower4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower4, -7);
    lv_obj_set_y(ui_sunflower4, 118);
    lv_obj_set_align(ui_sunflower4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sunflower5 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower5, &ui_img_sunflower5_png);
    lv_obj_set_width(ui_sunflower5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower5, -13);
    lv_obj_set_y(ui_sunflower5, 94);
    lv_obj_set_align(ui_sunflower5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sunflower6 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower6, &ui_img_sunflower6_png);
    lv_obj_set_width(ui_sunflower6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower6, -7);
    lv_obj_set_y(ui_sunflower6, 78);
    lv_obj_set_align(ui_sunflower6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sunflower7 = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_sunflower7, &ui_img_sunflower7_png);
    lv_obj_set_width(ui_sunflower7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sunflower7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sunflower7, -8);
    lv_obj_set_y(ui_sunflower7, 72);
    lv_obj_set_align(ui_sunflower7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunflower7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunflower7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_message = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_message, &ui_img_1083307527);
    lv_obj_set_width(ui_message, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_message, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_message, 205);
    lv_obj_set_y(ui_message, -128);
    lv_obj_set_align(ui_message, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_message, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_message, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_message, 300);

    ui_Label4 = lv_label_create(ui_message);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 2);
    lv_obj_set_y(ui_Label4, -10);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "3333333333333");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backhome = lv_img_create(ui_sunflowerscreen);
    lv_img_set_src(ui_backhome, &ui_img_zen_prevgarden_png);
    lv_obj_set_width(ui_backhome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backhome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backhome, 201);
    lv_obj_set_y(ui_backhome, 181);
    lv_obj_set_align(ui_backhome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backhome, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backhome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Insectremoval1, ui_event_Insectremoval1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fertilize1, ui_event_fertilize1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watering1, ui_event_watering1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_healthlabel1, ui_event_healthlabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statelabel1, ui_event_statelabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_humiditylabel1, ui_event_humiditylabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temperaturelabel1, ui_event_temperaturelabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightlabel1, ui_event_lightlabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weatherlabel1, ui_event_weatherlabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seasonlabel1, ui_event_seasonlabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Illustrated1, ui_event_Illustrated1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_next1, ui_event_next1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_getseed1, ui_event_getseed1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plantstagetextarea1, ui_event_plantstagetextarea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plant1, ui_event_plant1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_achivevmentimage1, ui_event_achivevmentimage1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_growthstagelabel1, ui_event_growthstagelabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower2, ui_event_sunflower2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower3, ui_event_sunflower3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower4, ui_event_sunflower4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower5, ui_event_sunflower5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower6, ui_event_sunflower6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sunflower7, ui_event_sunflower7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label4, ui_event_Label4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backhome, ui_event_backhome, LV_EVENT_ALL, NULL);

}

void ui_sunflowerscreen_screen_destroy(void)
{
    if(ui_sunflowerscreen) lv_obj_del(ui_sunflowerscreen);

    // NULL screen variables
    ui_sunflowerscreen = NULL;
    ui_background = NULL;
    ui_Insectremoval1 = NULL;
    ui_fertilize1 = NULL;
    ui_watering1 = NULL;
    ui_health1 = NULL;
    ui_healthlabel1 = NULL;
    ui_healthImage1 = NULL;
    ui_state1 = NULL;
    ui_statelabel1 = NULL;
    ui_stateImage1 = NULL;
    ui_humidity1 = NULL;
    ui_humiditylabel1 = NULL;
    ui_humidityImage1 = NULL;
    ui_temperature1 = NULL;
    ui_temperaturelabel1 = NULL;
    ui_temperatureImage1 = NULL;
    ui_light1 = NULL;
    ui_lightlabel1 = NULL;
    ui_lightImage1 = NULL;
    ui_weather1 = NULL;
    ui_weatherlabel1 = NULL;
    ui_weatherimage1 = NULL;
    ui_season1 = NULL;
    ui_seasonimage1 = NULL;
    ui_seasonlabel1 = NULL;
    ui_Illustrated1 = NULL;
    ui_next1 = NULL;
    ui_droplets1 = NULL;
    ui_getseed1 = NULL;
    ui_plantstagetextarea1 = NULL;
    ui_plant1 = NULL;
    ui_plantimg1 = NULL;
    ui_plantlabel1 = NULL;
    ui_achivevment1 = NULL;
    ui_achivevmentimage1 = NULL;
    ui_achivevmentlabel1 = NULL;
    ui_growthstage = NULL;
    ui_growthstageimage1 = NULL;
    ui_growthstagelabel1 = NULL;
    ui_sunflower1 = NULL;
    ui_sunflower2 = NULL;
    ui_sunflower3 = NULL;
    ui_sunflower4 = NULL;
    ui_sunflower5 = NULL;
    ui_sunflower6 = NULL;
    ui_sunflower7 = NULL;
    ui_message = NULL;
    ui_Label4 = NULL;
    ui_backhome = NULL;

}
