// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_storeScreen_screen_init(void)
{
    ui_storeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_storeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_achievementbg = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_achievementbg, &ui_img_letterbg__png);
    lv_obj_set_width(ui_achievementbg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_achievementbg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_achievementbg, -4);
    lv_obj_set_y(ui_achievementbg, 5);
    lv_obj_set_align(ui_achievementbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_achievementbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_achievementbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_achievementbg, 600);

    ui_Image2 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image2, &ui_img_grass__png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -334);
    lv_obj_set_y(ui_Image2, 114);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image3, &ui_img_grass__png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -334);
    lv_obj_set_y(ui_Image3, -8);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image4, &ui_img_grass__png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 346);
    lv_obj_set_y(ui_Image4, 130);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image5, &ui_img_grass__png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 347);
    lv_obj_set_y(ui_Image5, 7);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image6, &ui_img_grass__png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 349);
    lv_obj_set_y(ui_Image6, -119);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image9, &ui_img_grass__png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -334);
    lv_obj_set_y(ui_Image9, -128);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_commoditycannibal = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_commoditycannibal, &ui_img_hoedirtsnow__png);
    lv_obj_set_width(ui_commoditycannibal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_commoditycannibal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_commoditycannibal, -137);
    lv_obj_set_y(ui_commoditycannibal, 116);
    lv_obj_set_align(ui_commoditycannibal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_commoditycannibal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_commoditycannibal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_commoditycannibal, 128);

    ui_commoditycactus = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_commoditycactus, &ui_img_hoedirt1_png);
    lv_obj_set_width(ui_commoditycactus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_commoditycactus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_commoditycactus, 211);
    lv_obj_set_y(ui_commoditycactus, -32);
    lv_obj_set_align(ui_commoditycactus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_commoditycactus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_commoditycactus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_commoditycactus, 128);

    ui_commoditytomato = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_commoditytomato, &ui_img_hoedirt1_png);
    lv_obj_set_width(ui_commoditytomato, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_commoditytomato, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_commoditytomato, -11);
    lv_obj_set_y(ui_commoditytomato, -30);
    lv_obj_set_align(ui_commoditytomato, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_commoditytomato, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_commoditytomato, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_commoditytomato, 128);

    ui_commoditysunflower = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_commoditysunflower, &ui_img_hoedirt1_png);
    lv_obj_set_width(ui_commoditysunflower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_commoditysunflower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_commoditysunflower, -235);
    lv_obj_set_y(ui_commoditysunflower, -30);
    lv_obj_set_align(ui_commoditysunflower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_commoditysunflower, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_commoditysunflower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_commoditysunflower, 128);

    ui_Image8 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image8, &ui_img_hoedirtsnow__png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 113);
    lv_obj_set_y(ui_Image8, 117);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 128);

    ui_Image33 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image33, &ui_img_sunflower7_png);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image33, -237);
    lv_obj_set_y(ui_Image33, -100);
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image34 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image34, &ui_img_tomato7_png);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image34, -13);
    lv_obj_set_y(ui_Image34, -106);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image34, 220);

    ui_Image35 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image35, &ui_img_cacuts7_png);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image35, 234);
    lv_obj_set_y(ui_Image35, -92);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image36 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image36, &ui_img_cannibal7_png);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image36, -138);
    lv_obj_set_y(ui_Image36, 89);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buy1 = lv_btn_create(ui_storeScreen);
    lv_obj_set_width(ui_buy1, 73);
    lv_obj_set_height(ui_buy1, 31);
    lv_obj_set_x(ui_buy1, -242);
    lv_obj_set_y(ui_buy1, 33);
    lv_obj_set_align(ui_buy1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buy1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buy1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buy1, lv_color_hex(0xF8D52D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buy1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_buy1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "购买");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x0BAF1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buy2 = lv_btn_create(ui_storeScreen);
    lv_obj_set_width(ui_buy2, 73);
    lv_obj_set_height(ui_buy2, 31);
    lv_obj_set_x(ui_buy2, -13);
    lv_obj_set_y(ui_buy2, 32);
    lv_obj_set_align(ui_buy2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buy2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buy2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buy2, lv_color_hex(0xF8D52D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buy2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_buy2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "购买");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0BAF1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buy3 = lv_btn_create(ui_storeScreen);
    lv_obj_set_width(ui_buy3, 73);
    lv_obj_set_height(ui_buy3, 31);
    lv_obj_set_x(ui_buy3, 210);
    lv_obj_set_y(ui_buy3, 32);
    lv_obj_set_align(ui_buy3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buy3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buy3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buy3, lv_color_hex(0xF8D52D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buy3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_buy3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "购买");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x0BAF1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buy4 = lv_btn_create(ui_storeScreen);
    lv_obj_set_width(ui_buy4, 73);
    lv_obj_set_height(ui_buy4, 31);
    lv_obj_set_x(ui_buy4, -134);
    lv_obj_set_y(ui_buy4, 171);
    lv_obj_set_align(ui_buy4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buy4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buy4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buy4, lv_color_hex(0xF8D52D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buy4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_buy4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "购买");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x0BAF1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_money = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_money, &ui_img_901739709);
    lv_obj_set_width(ui_money, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_money, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_money, 181);
    lv_obj_set_y(ui_money, 149);
    lv_obj_set_align(ui_money, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_money, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_money, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_moneymessage = lv_label_create(ui_storeScreen);
    lv_obj_set_width(ui_moneymessage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moneymessage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moneymessage, 239);
    lv_obj_set_y(ui_moneymessage, 156);
    lv_obj_set_align(ui_moneymessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_moneymessage, "$5644");

    ui_Label8 = lv_label_create(ui_storeScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -240);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "$1000");

    ui_Label13 = lv_label_create(ui_storeScreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -13);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "$1200");

    ui_Label14 = lv_label_create(ui_storeScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 208);
    lv_obj_set_y(ui_Label14, 1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "$2000");

    ui_Label15 = lv_label_create(ui_storeScreen);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -135);
    lv_obj_set_y(ui_Label15, 143);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "$4000");

    ui_Label12 = lv_label_create(ui_storeScreen);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 113);
    lv_obj_set_y(ui_Label12, 84);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "..............");

    ui_Image7 = lv_img_create(ui_storeScreen);
    lv_img_set_src(ui_Image7, &ui_img_zen_prevgarden_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -258);
    lv_obj_set_y(ui_Image7, 188);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_buy1, ui_event_buy1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buy2, ui_event_buy2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buy3, ui_event_buy3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buy4, ui_event_buy4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_moneymessage, ui_event_moneymessage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);

}
