// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STORESCREEN_H
#define UI_STORESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_storeScreen
extern void ui_storeScreen_screen_init(void);
extern void ui_storeScreen_screen_destroy(void);
extern lv_obj_t * ui_storeScreen;
extern lv_obj_t * ui_achievementbg;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_commoditycannibal;
extern lv_obj_t * ui_commoditycactus;
extern lv_obj_t * ui_commoditytomato;
extern lv_obj_t * ui_commoditysunflower;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
extern void ui_event_buy1(lv_event_t * e);
extern lv_obj_t * ui_buy1;
extern lv_obj_t * ui_Label3;
extern void ui_event_buy2(lv_event_t * e);
extern lv_obj_t * ui_buy2;
extern lv_obj_t * ui_Label6;
extern void ui_event_buy3(lv_event_t * e);
extern lv_obj_t * ui_buy3;
extern lv_obj_t * ui_Label5;
extern void ui_event_buy4(lv_event_t * e);
extern lv_obj_t * ui_buy4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_money;
extern void ui_event_moneymessage(lv_event_t * e);
extern lv_obj_t * ui_moneymessage;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label12;
extern void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

