// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SUNFLOWERSCREEN_H
#define UI_SUNFLOWERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sunflowerscreen
extern void ui_sunflowerscreen_screen_init(void);
extern void ui_sunflowerscreen_screen_destroy(void);
extern lv_obj_t * ui_sunflowerscreen;
extern lv_obj_t * ui_background;
extern void ui_event_Insectremoval1(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval1;
extern void ui_event_fertilize1(lv_event_t * e);
extern lv_obj_t * ui_fertilize1;
extern void ui_event_watering1(lv_event_t * e);
extern lv_obj_t * ui_watering1;
extern lv_obj_t * ui_health1;
extern void ui_event_healthlabel1(lv_event_t * e);
extern lv_obj_t * ui_healthlabel1;
extern lv_obj_t * ui_healthImage1;
extern lv_obj_t * ui_state1;
extern void ui_event_statelabel1(lv_event_t * e);
extern lv_obj_t * ui_statelabel1;
extern lv_obj_t * ui_stateImage1;
extern lv_obj_t * ui_humidity1;
extern void ui_event_humiditylabel1(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel1;
extern lv_obj_t * ui_humidityImage1;
extern lv_obj_t * ui_temperature1;
extern void ui_event_temperaturelabel1(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel1;
extern lv_obj_t * ui_temperatureImage1;
extern lv_obj_t * ui_light1;
extern void ui_event_lightlabel1(lv_event_t * e);
extern lv_obj_t * ui_lightlabel1;
extern lv_obj_t * ui_lightImage1;
extern lv_obj_t * ui_weather1;
extern void ui_event_weatherlabel1(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel1;
extern lv_obj_t * ui_weatherimage1;
extern lv_obj_t * ui_season1;
extern lv_obj_t * ui_seasonimage1;
extern void ui_event_seasonlabel1(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel1;
extern void ui_event_Illustrated1(lv_event_t * e);
extern lv_obj_t * ui_Illustrated1;
extern void ui_event_next1(lv_event_t * e);
extern lv_obj_t * ui_next1;
extern lv_obj_t * ui_droplets1;
extern void ui_event_getseed1(lv_event_t * e);
extern lv_obj_t * ui_getseed1;
extern void ui_event_plantstagetextarea1(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea1;
extern void ui_event_plant1(lv_event_t * e);
extern lv_obj_t * ui_plant1;
extern lv_obj_t * ui_plantimg1;
extern lv_obj_t * ui_plantlabel1;
extern lv_obj_t * ui_achivevment1;
extern void ui_event_achivevmentimage1(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage1;
extern lv_obj_t * ui_achivevmentlabel1;
extern lv_obj_t * ui_growthstage;
extern lv_obj_t * ui_growthstageimage1;
extern void ui_event_growthstagelabel1(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel1;
extern lv_obj_t * ui_sunflower1;
extern void ui_event_sunflower2(lv_event_t * e);
extern lv_obj_t * ui_sunflower2;
extern void ui_event_sunflower3(lv_event_t * e);
extern lv_obj_t * ui_sunflower3;
extern void ui_event_sunflower4(lv_event_t * e);
extern lv_obj_t * ui_sunflower4;
extern void ui_event_sunflower5(lv_event_t * e);
extern lv_obj_t * ui_sunflower5;
extern void ui_event_sunflower6(lv_event_t * e);
extern lv_obj_t * ui_sunflower6;
extern void ui_event_sunflower7(lv_event_t * e);
extern lv_obj_t * ui_sunflower7;
extern lv_obj_t * ui_message;
extern void ui_event_Label4(lv_event_t * e);
extern lv_obj_t * ui_Label4;
extern void ui_event_backhome(lv_event_t * e);
extern lv_obj_t * ui_backhome;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

