// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TOMATOSCREEN_H
#define UI_TOMATOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tomatoscreen
extern void ui_tomatoscreen_screen_init(void);
extern void ui_tomatoscreen_screen_destroy(void);
extern lv_obj_t * ui_tomatoscreen;
extern lv_obj_t * ui_background2;
extern void ui_event_Insectremoval2(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval2;
extern void ui_event_fertilize2(lv_event_t * e);
extern lv_obj_t * ui_fertilize2;
extern void ui_event_watering2(lv_event_t * e);
extern lv_obj_t * ui_watering2;
extern lv_obj_t * ui_health2;
extern void ui_event_healthlabel2(lv_event_t * e);
extern lv_obj_t * ui_healthlabel2;
extern lv_obj_t * ui_healthImage2;
extern lv_obj_t * ui_state2;
extern void ui_event_statelabel2(lv_event_t * e);
extern lv_obj_t * ui_statelabel2;
extern lv_obj_t * ui_stateImage2;
extern lv_obj_t * ui_humidity2;
extern void ui_event_humiditylabel2(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel2;
extern lv_obj_t * ui_humidityImage2;
extern lv_obj_t * ui_temperature2;
extern void ui_event_temperaturelabel2(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel2;
extern lv_obj_t * ui_temperatureImage2;
extern lv_obj_t * ui_light2;
extern void ui_event_lightlabel2(lv_event_t * e);
extern lv_obj_t * ui_lightlabel2;
extern lv_obj_t * ui_lightImage2;
extern lv_obj_t * ui_weather2;
extern void ui_event_weatherlabel2(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel2;
extern lv_obj_t * ui_weatherimage2;
extern lv_obj_t * ui_season2;
extern lv_obj_t * ui_seasonimage2;
extern void ui_event_seasonlabel2(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel2;
extern void ui_event_Illustrated2(lv_event_t * e);
extern lv_obj_t * ui_Illustrated2;
extern void ui_event_next2(lv_event_t * e);
extern lv_obj_t * ui_next2;
extern lv_obj_t * ui_droplets2;
extern void ui_event_getseed2(lv_event_t * e);
extern lv_obj_t * ui_getseed2;
extern void ui_event_plantstagetextarea2(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea2;
extern void ui_event_plant2(lv_event_t * e);
extern lv_obj_t * ui_plant2;
extern lv_obj_t * ui_plantimg2;
extern lv_obj_t * ui_plantlabel2;
extern lv_obj_t * ui_achivevment2;
extern void ui_event_achivevmentimage2(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage2;
extern lv_obj_t * ui_achivevmentlabel2;
extern lv_obj_t * ui_growthstage1;
extern lv_obj_t * ui_growthstageimage2;
extern void ui_event_growthstagelabel2(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel2;
extern void ui_event_back1(lv_event_t * e);
extern lv_obj_t * ui_back1;
extern lv_obj_t * ui_tomato1;
extern void ui_event_tomato2(lv_event_t * e);
extern lv_obj_t * ui_tomato2;
extern void ui_event_tomato3(lv_event_t * e);
extern lv_obj_t * ui_tomato3;
extern void ui_event_tomato4(lv_event_t * e);
extern lv_obj_t * ui_tomato4;
extern void ui_event_tomato5(lv_event_t * e);
extern lv_obj_t * ui_tomato5;
extern void ui_event_tomato6(lv_event_t * e);
extern lv_obj_t * ui_tomato6;
extern void ui_event_tomato7(lv_event_t * e);
extern lv_obj_t * ui_tomato7;
extern lv_obj_t * ui_message2;
extern void ui_event_Label9(lv_event_t * e);
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

