// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "plant_simulation.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

extern PlantState* plant;
extern PlantState* tomato;
extern PlantState* cactus;
extern PlantState* cannibal_flower;
extern Environment* env;
extern User* user;
extern Commodity* commodity;

extern lv_obj_t * ui_temperaturelabel1;
bool exist_plant = false;


void plant_insert_removal(lv_event_t * e)
{
	pest_control(plant);
	//plant->health = plant->health + 5;
	// Your code here
}

void plant_fertilize(lv_event_t * e)
{
	// Your code here
	fertilize(plant);
	//plant->health = plant->health + 5;
}

void plant_watering(lv_event_t * e)
{
	// Your code here
	watering(plant);
	//plant->health = plant->health + 5;
}

// void get_seed(lv_event_t * e)
// {
// 	const char* type_str[] = {"向日葵", "西红柿", "仙人掌", "食人花"};
// 	// Your code here
//     srand(time(NULL));
    
//     // 生成0~3的随机数
//     PlantType type = rand() % 4;
    
//     printf("新的植物！%s\n", type_str[type]);
// 	lv_textarea_add_text(ui_plantstagetextarea1, type_str[type]);

// }

// void grow_plant(lv_event_t * e)
// {
// 	init_plant(plant, SUNFLOWER, 2);
// 	// Your code here
// 	exist_plant = true;
// 	lv_obj_add_state(ui_plant1, LV_STATE_DISABLED);
// }



void healthchange(lv_event_t * e)
{
	// Your code here
	uint8_t health = plant->health; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "健康: %d/100", health);
    lv_label_set_text(ui_healthlabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_healthlabel1);
}

void agechange(lv_event_t * e)
{
	// Your code here
	uint32_t age = plant->age; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "年龄: %d天", age);
    lv_label_set_text(ui_statelabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_statelabel1);
}

void humiditychange(lv_event_t * e)
{
	// Your code here
	uint8_t humidity = env->humidity; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "湿度: %d", humidity);
    lv_label_set_text(ui_humiditylabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_humiditylabel1);
}

void temperaturechange(lv_event_t * e)
{
	// 获取当前对象
    //ui_temperaturelabel1 = lv_event_get_target(e);
    
    // 更新标签内容示例
    
    uint8_t temperature = env->temperature; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "温度: %d度", temperature);
    lv_label_set_text(ui_temperaturelabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_temperaturelabel1);
	// Your code here
}

void lightchange(lv_event_t * e)
{
	// Your code here
	uint8_t light = env->light; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "光照: %d", light);
    lv_label_set_text(ui_lightlabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_lightlabel1);
}

void weatherchange(lv_event_t * e)
{
	// Your code here
	const char* weather_str[] = {"Clear", "Cloudy", "Rainy", "Snowy", "Windy"};
	WeatherType weather = env->weather; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s", weather_str[weather]);
    lv_label_set_text(ui_weatherlabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_weatherlabel1);
    lv_obj_t *scr = lv_scr_act();
    switch(weather){
        case 0:
            lv_obj_set_style_bg_img_src(scr, &ui_img_1664587152, LV_PART_MAIN | LV_STATE_DEFAULT);
            
            break;
        case 1:
            lv_obj_set_style_bg_img_src(scr, &ui_img_1772208564, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 2:
            lv_obj_set_style_bg_img_src(scr, &ui_img_145349238, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 3:
            lv_obj_set_style_bg_img_src(scr, &ui_img_145351288, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 4:
            lv_obj_set_style_bg_img_src(scr, &ui_img_1224826616, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
    }
    lv_obj_invalidate(scr);
}

void seasonchange(lv_event_t * e)
{
	// Your code here
	const char* season_str[] = {"Spring", "Summer", "Autumn", "Winter"};
	uint8_t season = env->season; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s", season_str[season]);
    lv_label_set_text(ui_seasonlabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_seasonlabel1);
}

void growseed(lv_event_t * e)
{
	// Your code here
	
}


// void growsproutEvent(lv_event_t * e)
// {
// 	// Your code here
// 	// 设置图片透明度 (0-255, 0为完全透明，255为完全不透明)
// 	lv_obj_t * target = lv_event_get_target(e);
// 	lv_obj_add_flag(ui_seed1, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_clear_flag(ui_sprout1, LV_OBJ_FLAG_HIDDEN);
	
// 	//lv_obj_set_style_img_opa(ui_seed1, 255, 0);  // 50% 透明度
// 	//lv_obj_invalidate(ui_seed1);
// }

/////////////////////////////////////////////////////////////////////////////////////
// void growseeding(lv_event_t * e)
// {
// 	// Your code here
// 	lv_obj_add_flag(ui_sprout1, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_clear_flag(ui_seeding1, LV_OBJ_FLAG_HIDDEN);
// }

// void growmature(lv_event_t * e)
// {
// 	// Your code here
// 	lv_obj_add_flag(ui_seeding1, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_clear_flag(ui_mature1, LV_OBJ_FLAG_HIDDEN);
// }

// void growflowering(lv_event_t * e)
// {
// 	// Your code here
// 	lv_obj_add_flag(ui_mature1, LV_OBJ_FLAG_HIDDEN);
//     lv_obj_clear_flag(ui_flowering, LV_OBJ_FLAG_HIDDEN);
// }

void growthstagechange(lv_event_t * e)
{
	// Your code here
	const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	GrowthStage stage = plant->stage; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s(%u%%)", stage_str[stage], plant->growth);
    lv_label_set_text(ui_growthstagelabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_growthstagelabel1);
}

void switch2illustratedscreen(lv_event_t * e)
{
	FILE* fp = fopen("sunflower.txt", "r");
	if(fp == NULL) {
        fp = fopen("sunflower.txt", "r");
        if(fp == NULL) {
            perror("无法打开文件");
            
            return;
        }
    }
	char buffer[512] ;
	// 读取一行
    while(fgets(buffer, sizeof(buffer), fp) != NULL) {
        // 添加到文本区域
        lv_textarea_add_text(ui_illuTextArea, buffer);
        
        // 滚动到最新内容
        lv_textarea_set_cursor_pos(ui_illuTextArea, LV_TEXTAREA_CURSOR_LAST);
    } 

    // 读取完毕或出错
        if(feof(fp)) {
            printf("--- 文件读取完毕 ---\n");
        } else {
            printf("Error: 读取文件失败\n");
        }
        fclose(fp);
        fp = NULL;
	

	
	// Your code here
}


void message_plantstage(lv_event_t * e)
{
    const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	GrowthStage stage = plant->stage; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "植物%s了", stage_str[stage]);
    lv_label_set_text(ui_plantstagetextarea1, temp_str);
    lv_obj_clear_flag(ui_plantstagetextarea1, LV_OBJ_FLAG_HIDDEN);
    // 触发界面刷新
    lv_obj_invalidate(ui_plantstagetextarea1);
	// Your code here
    lv_obj_add_flag(ui_plantstagetextarea1, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflowerseed(lv_event_t * e)
{
	// Your code here
    //lv_obj_add_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
    if(plant->stage == SEED){
        init_plant(plant, SUNFLOWER, 2);
        lv_obj_clear_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
        exist_plant = true;
 	    lv_obj_add_state(ui_plant1, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant1, LV_STATE_DISABLED);
    }
    

}

void show_sunflower2(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower3(lv_event_t * e)
{
	// Your code here
    // lv_obj_add_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_clear_flag(ui_sunflower3, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower4(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower4, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower5(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower5, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower6(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower6, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower7(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower7, LV_OBJ_FLAG_HIDDEN);
}

void show_message(lv_event_t * e)
{
	// Your code here
    const char* buffer = get_plant_needs(plant);
    lv_label_set_text(ui_Label4, buffer);
    lv_obj_invalidate(ui_Label4);
}

void illu_img_change(lv_event_t * e)
{
	// Your code here
}

void illu_label_change(lv_event_t * e)
{
	// Your code here
}

void buy_sunflower(lv_event_t * e)
{
    buy_plant(user, commodity, SUNFLOWER);
    lv_label_set_text(ui_Label3, "已购买");
    lv_obj_invalidate(ui_Label3);
	// Your code here
}

void buy_tomato(lv_event_t * e)
{
    buy_plant(user, commodity, TOMATO);
    lv_label_set_text(ui_Label6, "已购买");
    lv_obj_invalidate(ui_Label6);
	// Your code here
}

void buy_catus(lv_event_t * e)
{
    buy_plant(user, commodity, CACTUS);
    lv_label_set_text(ui_Label5, "已购买");
    lv_obj_invalidate(ui_Label7);
	// Your code here
}

void buy_cannibal(lv_event_t * e)
{
    buy_plant(user, commodity, CANNIBAL_FLOWERS);
    lv_label_set_text(ui_Label7, "已购买");
    lv_obj_invalidate(ui_Label3);
	// Your code here
}

void show_money(lv_event_t * e)
{
    uint32_t coins = user->coins; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%d", coins);
    lv_label_set_text(ui_moneymessage, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_moneymessage);
	// Your code here
}

void show_tomatoseed(lv_event_t * e)
{
	// Your code here
    if(tomato->stage == SEED){
        init_plant(tomato, TOMATO, 2);
        lv_obj_clear_flag(ui_tomato1, LV_OBJ_FLAG_HIDDEN);
        exist_plant = true;
 	    lv_obj_add_state(ui_plant2, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_tomato1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant2, LV_STATE_DISABLED);
    }
}

void show_tomato2(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato2, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato3(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato3, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato4(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato4, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato5(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato5, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato6(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato6, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato7(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato7, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactusseed(lv_event_t * e)
{
    if(cactus->stage == SEED){
        init_plant(cactus, CACTUS, 2);
        lv_obj_clear_flag(ui_Cactus1, LV_OBJ_FLAG_HIDDEN);
        exist_plant = true;
 	    lv_obj_add_state(ui_plant3, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_Cactus1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant3, LV_STATE_DISABLED);
    }
	// Your code here
}

void show_cactus2(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus2, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus3(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus3, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus4(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus4, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus5(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus5, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus6(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus6, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus7(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus7, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cannibalseed(lv_event_t * e)
{
    if(cannibal_flower->stage == SEED){
        init_plant(cannibal_flower, CANNIBAL_FLOWERS, 2);
        lv_obj_clear_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN);
        exist_plant = true;
 	    lv_obj_add_state(ui_plant4, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant4, LV_STATE_DISABLED);
    }
	// Your code here
}

void show_canniabl2(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal2, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl3(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal3, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl4(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal4, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl5(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal5, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl6(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal6, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl7(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal7, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}
