// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "plant_simulation.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

extern PlantState* sunflower;
extern PlantState* tomato;
extern PlantState* cactus;
extern PlantState* cannibal_flower;
extern Environment* env;
extern User* user;
extern Commodity* commodity;

extern lv_obj_t * ui_temperaturelabel1;
bool isplant[4] = {0};


void plant_insert_removal(lv_event_t * e)
{
	pest_control(sunflower);
	//plant->health = plant->health + 5;
	// Your code here
}

void plant_insert_removal2(lv_event_t * e)
{
	pest_control(tomato);
	//plant->health = plant->health + 5;
	// Your code here
}

void plant_insert_removal3(lv_event_t * e)
{
	pest_control(cactus);
	//plant->health = plant->health + 5;
	// Your code here
}

void plant_insert_removal4(lv_event_t * e)
{
	pest_control(cannibal_flower);
	//plant->health = plant->health + 5;
	// Your code here
}

void plant_fertilize(lv_event_t * e)
{
	// Your code here
	fertilize(sunflower);
	//plant->health = plant->health + 5;
}
void plant_fertilize2(lv_event_t * e)
{
	// Your code here
	fertilize(tomato);
	//plant->health = plant->health + 5;
}
void plant_fertilize3(lv_event_t * e)
{
	// Your code here
	fertilize(cactus);
	//plant->health = plant->health + 5;
}
void plant_fertilize4(lv_event_t * e)
{
	// Your code here
	fertilize(cannibal_flower);
	//plant->health = plant->health + 5;
}


void plant_watering(lv_event_t * e)
{
	// Your code here
	watering(sunflower);
	//plant->health = plant->health + 5;
}
void plant_watering2(lv_event_t * e)
{
	// Your code here
	watering(tomato);
	//plant->health = plant->health + 5;
}
void plant_watering3(lv_event_t * e)
{
	// Your code here
	watering(cactus);
	//plant->health = plant->health + 5;
}
void plant_watering4(lv_event_t * e)
{
	// Your code here
	watering(cannibal_flower);
	//plant->health = plant->health + 5;
}



void healthchange(lv_event_t * e)
{
	// Your code here
	uint8_t health = sunflower->health; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "健康: %d/100", health);
    lv_label_set_text(ui_healthlabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_healthlabel1);
}
void healthchange2(lv_event_t * e)
{
	// Your code here
	uint8_t health = tomato->health; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "健康: %d/100", health);
    lv_label_set_text(ui_healthlabel2, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_healthlabel2);
}

void healthchange3(lv_event_t * e)
{
	// Your code here
	uint8_t health = cactus->health; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "健康: %d/100", health);
    lv_label_set_text(ui_healthlabel3, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_healthlabel3);
}
void healthchange4(lv_event_t * e)
{
	// Your code here
	uint8_t health = cannibal_flower->health; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "健康: %d/100", health);
    lv_label_set_text(ui_healthlabel4, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_healthlabel4);
}


void agechange(lv_event_t * e)
{
	// Your code here
	uint32_t age = sunflower->age; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "年龄: %d天", age);
    lv_label_set_text(ui_statelabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_statelabel1);
}

void agechange2(lv_event_t * e)
{
	// Your code here
	uint32_t age = tomato->age; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "年龄: %d天", age);
    lv_label_set_text(ui_statelabel2, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_statelabel2);
}
void agechange3(lv_event_t * e)
{
	// Your code here
	uint32_t age = cactus->age; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "年龄: %d天", age);
    lv_label_set_text(ui_statelabel3, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_statelabel3);
}
void agechange4(lv_event_t * e)
{
	// Your code here
	uint32_t age = cannibal_flower->age; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "年龄: %d天", age);
    lv_label_set_text(ui_statelabel4, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_statelabel4);
}

void humiditychange(lv_event_t * e)
{
	// Your code here
	uint8_t humidity = env->humidity; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "湿度: %d", humidity);
    lv_label_set_text(ui_humiditylabel1, temp_str);
    lv_label_set_text(ui_humiditylabel2, temp_str);
    lv_label_set_text(ui_humiditylabel3, temp_str);
    lv_label_set_text(ui_humiditylabel4, temp_str);
    // 触发界面刷新
    lv_obj_invalidate(ui_humiditylabel1);
    lv_obj_invalidate(ui_humiditylabel2);
    lv_obj_invalidate(ui_humiditylabel3);
    lv_obj_invalidate(ui_humiditylabel4);

}

void temperaturechange(lv_event_t * e)
{
	// 获取当前对象
    //ui_temperaturelabel1 = lv_event_get_target(e);
    
    // 更新标签内容示例
    
    uint8_t temperature = env->temperature; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "温度: %d度", temperature);
    lv_label_set_text(ui_temperaturelabel1, temp_str);
    lv_label_set_text(ui_temperaturelabel2, temp_str);
    lv_label_set_text(ui_temperaturelabel3, temp_str);
    lv_label_set_text(ui_temperaturelabel4, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_temperaturelabel1);
    lv_obj_invalidate(ui_temperaturelabel2);
    lv_obj_invalidate(ui_temperaturelabel3);
    lv_obj_invalidate(ui_temperaturelabel4);

	// Your code here
}

void lightchange(lv_event_t * e)
{
	// Your code here
	uint8_t light = env->light; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "光照: %d", light);
    lv_label_set_text(ui_lightlabel1, temp_str);
    lv_label_set_text(ui_lightlabel2, temp_str);
    lv_label_set_text(ui_lightlabel3, temp_str);
    lv_label_set_text(ui_lightlabel4, temp_str);

    // 触发界面刷新
    lv_obj_invalidate(ui_lightlabel1);
    lv_obj_invalidate(ui_lightlabel2);
    lv_obj_invalidate(ui_lightlabel3);
    lv_obj_invalidate(ui_lightlabel4);
}

void weatherchange(lv_event_t * e)
{
	// Your code here
	const char* weather_str[] = {"Clear", "Cloudy", "Rainy", "Snowy", "Windy"};
	WeatherType weather = env->weather; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s", weather_str[weather]);
    lv_label_set_text(ui_weatherlabel1, temp_str);
    lv_label_set_text(ui_weatherlabel2, temp_str);
    lv_label_set_text(ui_weatherlabel3, temp_str);
    lv_label_set_text(ui_weatherlabel4, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_weatherlabel1);
    lv_obj_invalidate(ui_weatherlabel2);
    lv_obj_invalidate(ui_weatherlabel3);
    lv_obj_invalidate(ui_weatherlabel4);
    lv_obj_t *scr = lv_scr_act();
    switch(weather){
        case 0:
            lv_obj_set_style_bg_img_src(scr, &ui_img_1664587152, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 1:
            lv_obj_set_style_bg_img_src(scr, &ui_img_1772208564, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 2:
            lv_obj_set_style_bg_img_src(scr, &ui_img_145349238, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 3:
            lv_obj_set_style_bg_img_src(scr, &ui_img_145351288, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 4:
            lv_obj_set_style_bg_img_src(scr, &ui_img_1224826616, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
    }
    lv_obj_invalidate(scr);
}

void seasonchange(lv_event_t * e)
{
	// Your code here
	const char* season_str[] = {"Spring", "Summer", "Autumn", "Winter"};
	uint8_t season = env->season; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s", season_str[season]);
    lv_label_set_text(ui_seasonlabel1, temp_str);
    lv_label_set_text(ui_seasonlabel2, temp_str);
    lv_label_set_text(ui_seasonlabel3, temp_str);
    lv_label_set_text(ui_seasonlabel4, temp_str);
    // 触发界面刷新
    lv_obj_invalidate(ui_seasonlabel1);
    lv_obj_invalidate(ui_seasonlabel2);
    lv_obj_invalidate(ui_seasonlabel3);
    lv_obj_invalidate(ui_seasonlabel4);
}

void growseed(lv_event_t * e){}

void growthstagechange(lv_event_t * e)
{
	// Your code here
	const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	GrowthStage stage = sunflower->stage; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s(%u%%)", stage_str[stage], sunflower->growth);
    lv_label_set_text(ui_growthstagelabel1, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_growthstagelabel1);
}


void growthstagechange2(lv_event_t * e)
{
	// Your code here
	const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	GrowthStage stage = tomato->stage; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s(%u%%)", stage_str[stage], tomato->growth);
    lv_label_set_text(ui_growthstagelabel2, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_growthstagelabel2);
}

void growthstagechange3(lv_event_t * e)
{
	// Your code here
	const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	GrowthStage stage = cactus->stage; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s(%u%%)", stage_str[stage], cactus->growth);
    lv_label_set_text(ui_growthstagelabel3, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_growthstagelabel3);
}
void growthstagechange4(lv_event_t * e)
{
	// Your code here
	const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	GrowthStage stage = cannibal_flower->stage; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%s(%u%%)", stage_str[stage], cannibal_flower->growth);
    lv_label_set_text(ui_growthstagelabel4, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_growthstagelabel4);
}

void switch2illustratedscreen(lv_event_t * e)
{
	FILE* fp = fopen("sunflower.txt", "r");
	if(fp == NULL) {
        fp = fopen("sunflower.txt", "r");
        if(fp == NULL) {
            perror("无法打开文件");
            
            return;
        }
    }
	char buffer[512] ;
	// 读取一行
    while(fgets(buffer, sizeof(buffer), fp) != NULL) {
        // 添加到文本区域
        lv_textarea_add_text(ui_illuTextArea, buffer);
        
        // 滚动到最新内容
        lv_textarea_set_cursor_pos(ui_illuTextArea, LV_TEXTAREA_CURSOR_LAST);
    } 

    // 读取完毕或出错
        if(feof(fp)) {
            printf("--- 文件读取完毕 ---\n");
        } else {
            printf("Error: 读取文件失败\n");
        }
        fclose(fp);
        fp = NULL;
	

	
	// Your code here
}


void message_plantstage(lv_event_t * e)
{
    // const char* stage_str[] = {"种子", "发芽", "幼苗", "成熟", "开花", "结果"};
	// GrowthStage stage = sunflower->stage; 
    
    // // 使用格式化字符串更新温度显示
    // char temp_str[16];
    // snprintf(temp_str, sizeof(temp_str), "植物%s了", stage_str[stage]);
    // lv_label_set_text(ui_plantstagetextarea1, temp_str);
    // lv_obj_clear_flag(ui_plantstagetextarea1, LV_OBJ_FLAG_HIDDEN);
    // // 触发界面刷新
    // lv_obj_invalidate(ui_plantstagetextarea1);
	// // Your code here
    // lv_obj_add_flag(ui_plantstagetextarea1, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflowerseed(lv_event_t * e)
{
	// Your code here
    //lv_obj_add_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
    if(sunflower->stage == SEED){
        init_plant(sunflower, SUNFLOWER, 2);
        lv_obj_clear_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
        isplant[0] = true;
 	    lv_obj_add_state(ui_plant1, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant1, LV_STATE_DISABLED);
    }
    

}

void show_sunflower2(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower3(lv_event_t * e)
{
	// Your code here
    // lv_obj_add_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_clear_flag(ui_sunflower3, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower4(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower4, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower5(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower5, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower6(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower6, LV_OBJ_FLAG_HIDDEN);
}

void show_sunflower7(lv_event_t * e)
{
	// Your code here
    lv_obj_add_flag(ui_sunflower6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_sunflower7, LV_OBJ_FLAG_HIDDEN);
}

void show_message(lv_event_t * e)
{
	// Your code here
    const char* buffer = get_plant_needs(sunflower);
    lv_label_set_text(ui_Label4, buffer);
    lv_obj_invalidate(ui_Label4);
}

const char *get_obj_name(lv_obj_t *obj) {
    return (const char *)lv_obj_get_user_data(obj);
}

void illu_change(lv_event_t * e)
{
    const char* screen_str[] = {"ui_sunflowerscreen", 
        "ui_tomatoscreen", "ui_cactusscreen", "ui_cannibalscreen"};
	
	// Your code here
    lv_obj_t* current_screen = lv_scr_act();
    const char* screen_name = get_obj_name(current_screen);
    printf("%s\n", screen_name);
}

void illu_img_change(lv_event_t * e)
{

}

void illu_label_change(lv_event_t * e)
{
	// Your code here
}

void buy_sunflower(lv_event_t * e)
{
    buy_plant(user, commodity, SUNFLOWER);
    init_plant(sunflower, SUNFLOWER, 1);
    lv_label_set_text(ui_Label3, "已购买");
    lv_obj_invalidate(ui_Label3);
	// Your code here
}

void buy_tomato(lv_event_t * e)
{
    buy_plant(user, commodity, TOMATO);
    init_plant(tomato, TOMATO, 2);
    lv_label_set_text(ui_Label6, "已购买");
    lv_obj_invalidate(ui_Label6);
	// Your code here
}

void buy_catus(lv_event_t * e)
{
    
    buy_plant(user, commodity, CACTUS);
    init_plant(cactus, CACTUS, 2);
    lv_label_set_text(ui_Label5, "已购买");
    lv_obj_invalidate(ui_Label7);
	// Your code here
}

void buy_cannibal(lv_event_t * e)
{
    buy_plant(user, commodity, CANNIBAL_FLOWERS);
    init_plant(cannibal_flower, CANNIBAL_FLOWERS, 3);
    lv_label_set_text(ui_Label7, "已购买");
    lv_obj_invalidate(ui_Label3);
	// Your code here
}

void show_money(lv_event_t * e)
{
    uint32_t coins = user->coins; 
    
    // 使用格式化字符串更新温度显示
    char temp_str[16];
    snprintf(temp_str, sizeof(temp_str), "%d", coins);
    lv_label_set_text(ui_moneymessage, temp_str);
    
    // 触发界面刷新
    lv_obj_invalidate(ui_moneymessage);
	// Your code here
}

void show_tomatoseed(lv_event_t * e)
{
	// Your code here
        lv_obj_clear_flag(ui_tomato1, LV_OBJ_FLAG_HIDDEN);
        isplant[1] = true;
 	    lv_obj_add_state(ui_plant2, LV_STATE_DISABLED);
        user->plant_num = 1;
    
}

void show_tomato2(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato2, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato3(lv_event_t * e)
{
    // lv_obj_add_flag(ui_tomato2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_clear_flag(ui_tomato3, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato4(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato4, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato5(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato5, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato6(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato6, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_tomato7(lv_event_t * e)
{
    lv_obj_add_flag(ui_tomato6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_tomato7, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactusseed(lv_event_t * e)
{
    if(cactus->stage == SEED){
        
        lv_obj_clear_flag(ui_Cactus1, LV_OBJ_FLAG_HIDDEN);
        isplant[2] = true;
 	    lv_obj_add_state(ui_plant3, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_Cactus1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant3, LV_STATE_DISABLED);
    }
	// Your code here
}

void show_cactus2(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus2, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus3(lv_event_t * e)
{
    // lv_obj_add_flag(ui_Cactus2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_clear_flag(ui_Cactus3, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus4(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus4, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus5(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus5, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus6(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus6, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cactus7(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cactus6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cactus7, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_cannibalseed(lv_event_t * e)
{
    if(cannibal_flower->stage == SEED){
        
        lv_obj_clear_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN);
        isplant[3] = true;
 	    lv_obj_add_state(ui_plant4, LV_STATE_DISABLED);
        user->plant_num = 1;
    }
    else{
        lv_obj_clear_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN);
        //exist_plant = true;
 	    lv_obj_add_state(ui_plant4, LV_STATE_DISABLED);
    }
	// Your code here
}

void show_canniabl2(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal2, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl3(lv_event_t * e)
{
    // lv_obj_add_flag(ui_Cannibal2, LV_OBJ_FLAG_HIDDEN);
    // lv_obj_clear_flag(ui_Cannibal3, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl4(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal4, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl5(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal5, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl6(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal6, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}

void show_canniabl7(lv_event_t * e)
{
    lv_obj_add_flag(ui_Cannibal6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Cannibal7, LV_OBJ_FLAG_HIDDEN);
	// Your code here
}
