// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void wateringmove1_Animation(lv_obj_t * TargetObject, int delay);
void imageangle1_Animation(lv_obj_t * TargetObject, int delay);
void wateringback1_Animation(lv_obj_t * TargetObject, int delay);
void Opacityfull1_Animation(lv_obj_t * TargetObject, int delay);
void Opacityzero1_Animation(lv_obj_t * TargetObject, int delay);
void fertilizemove1_Animation(lv_obj_t * TargetObject, int delay);
void fertilizeback1_Animation(lv_obj_t * TargetObject, int delay);
void Insectremovalmove1_Animation(lv_obj_t * TargetObject, int delay);
void Insectremovalback1_Animation(lv_obj_t * TargetObject, int delay);
void plantstate_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_initscreen
void ui_initscreen_screen_init(void);
extern lv_obj_t * ui_initscreen;
extern lv_obj_t * ui_Label1;
void ui_event_getseedinit(lv_event_t * e);
extern lv_obj_t * ui_getseedinit;
extern lv_obj_t * ui_getseedlabelinit;
extern lv_obj_t * ui_getseedimginit;
// SCREEN: ui_sunflowerscreen
void ui_sunflowerscreen_screen_init(void);
extern lv_obj_t * ui_sunflowerscreen;
extern lv_obj_t * ui_background;
void ui_event_Insectremoval1(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval1;
void ui_event_fertilize1(lv_event_t * e);
extern lv_obj_t * ui_fertilize1;
void ui_event_watering1(lv_event_t * e);
extern lv_obj_t * ui_watering1;
extern lv_obj_t * ui_health1;
void ui_event_healthlabel1(lv_event_t * e);
extern lv_obj_t * ui_healthlabel1;
extern lv_obj_t * ui_healthImage1;
extern lv_obj_t * ui_state1;
void ui_event_statelabel1(lv_event_t * e);
extern lv_obj_t * ui_statelabel1;
extern lv_obj_t * ui_stateImage1;
extern lv_obj_t * ui_humidity1;
void ui_event_humiditylabel1(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel1;
extern lv_obj_t * ui_humidityImage1;
extern lv_obj_t * ui_temperature1;
void ui_event_temperaturelabel1(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel1;
extern lv_obj_t * ui_temperatureImage1;
extern lv_obj_t * ui_light1;
void ui_event_lightlabel1(lv_event_t * e);
extern lv_obj_t * ui_lightlabel1;
extern lv_obj_t * ui_lightImage1;
extern lv_obj_t * ui_weather1;
void ui_event_weatherlabel1(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel1;
extern lv_obj_t * ui_weatherimage1;
extern lv_obj_t * ui_season1;
extern lv_obj_t * ui_seasonimage1;
void ui_event_seasonlabel1(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel1;
void ui_event_Illustrated1(lv_event_t * e);
extern lv_obj_t * ui_Illustrated1;
void ui_event_next1(lv_event_t * e);
extern lv_obj_t * ui_next1;
extern lv_obj_t * ui_droplets1;
void ui_event_getseed1(lv_event_t * e);
extern lv_obj_t * ui_getseed1;
void ui_event_plantstagetextarea1(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea1;
void ui_event_plant1(lv_event_t * e);
extern lv_obj_t * ui_plant1;
extern lv_obj_t * ui_plantimg1;
extern lv_obj_t * ui_plantlabel1;
extern lv_obj_t * ui_achivevment1;
void ui_event_achivevmentimage1(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage1;
extern lv_obj_t * ui_achivevmentlabel1;
extern lv_obj_t * ui_growthstage;
extern lv_obj_t * ui_growthstageimage1;
void ui_event_growthstagelabel1(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel1;
extern lv_obj_t * ui_sunflower1;
void ui_event_sunflower2(lv_event_t * e);
extern lv_obj_t * ui_sunflower2;
void ui_event_sunflower3(lv_event_t * e);
extern lv_obj_t * ui_sunflower3;
void ui_event_sunflower4(lv_event_t * e);
extern lv_obj_t * ui_sunflower4;
void ui_event_sunflower5(lv_event_t * e);
extern lv_obj_t * ui_sunflower5;
void ui_event_sunflower6(lv_event_t * e);
extern lv_obj_t * ui_sunflower6;
void ui_event_sunflower7(lv_event_t * e);
extern lv_obj_t * ui_sunflower7;
extern lv_obj_t * ui_message;
void ui_event_Label4(lv_event_t * e);
extern lv_obj_t * ui_Label4;
void ui_event_backhome(lv_event_t * e);
extern lv_obj_t * ui_backhome;
// SCREEN: ui_IllustratedScreen
void ui_IllustratedScreen_screen_init(void);
extern lv_obj_t * ui_IllustratedScreen;
extern lv_obj_t * ui_illustratedbg;
extern lv_obj_t * ui_illuTextArea;
extern lv_obj_t * ui_illuImage;
void ui_event_back(lv_event_t * e);
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_illplant;
void ui_event_sunflower(lv_event_t * e);
extern lv_obj_t * ui_sunflower;
void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
// SCREEN: ui_storeScreen
void ui_storeScreen_screen_init(void);
extern lv_obj_t * ui_storeScreen;
extern lv_obj_t * ui_achievementbg;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_commoditycannibal;
extern lv_obj_t * ui_commoditycactus;
extern lv_obj_t * ui_commoditytomato;
extern lv_obj_t * ui_commoditysunflower;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
void ui_event_buy1(lv_event_t * e);
extern lv_obj_t * ui_buy1;
extern lv_obj_t * ui_Label3;
void ui_event_buy2(lv_event_t * e);
extern lv_obj_t * ui_buy2;
extern lv_obj_t * ui_Label6;
void ui_event_buy3(lv_event_t * e);
extern lv_obj_t * ui_buy3;
extern lv_obj_t * ui_Label5;
void ui_event_buy4(lv_event_t * e);
extern lv_obj_t * ui_buy4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_money;
void ui_event_moneymessage(lv_event_t * e);
extern lv_obj_t * ui_moneymessage;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label12;
void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
// SCREEN: ui_tomatoscreen
void ui_tomatoscreen_screen_init(void);
extern lv_obj_t * ui_tomatoscreen;
extern lv_obj_t * ui_background2;
void ui_event_Insectremoval2(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval2;
void ui_event_fertilize2(lv_event_t * e);
extern lv_obj_t * ui_fertilize2;
void ui_event_watering2(lv_event_t * e);
extern lv_obj_t * ui_watering2;
extern lv_obj_t * ui_health2;
void ui_event_healthlabel2(lv_event_t * e);
extern lv_obj_t * ui_healthlabel2;
extern lv_obj_t * ui_healthImage2;
extern lv_obj_t * ui_state2;
void ui_event_statelabel2(lv_event_t * e);
extern lv_obj_t * ui_statelabel2;
extern lv_obj_t * ui_stateImage2;
extern lv_obj_t * ui_humidity2;
void ui_event_humiditylabel2(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel2;
extern lv_obj_t * ui_humidityImage2;
extern lv_obj_t * ui_temperature2;
void ui_event_temperaturelabel2(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel2;
extern lv_obj_t * ui_temperatureImage2;
extern lv_obj_t * ui_light2;
void ui_event_lightlabel2(lv_event_t * e);
extern lv_obj_t * ui_lightlabel2;
extern lv_obj_t * ui_lightImage2;
extern lv_obj_t * ui_weather2;
void ui_event_weatherlabel2(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel2;
extern lv_obj_t * ui_weatherimage2;
extern lv_obj_t * ui_season2;
extern lv_obj_t * ui_seasonimage2;
void ui_event_seasonlabel2(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel2;
void ui_event_Illustrated2(lv_event_t * e);
extern lv_obj_t * ui_Illustrated2;
void ui_event_next2(lv_event_t * e);
extern lv_obj_t * ui_next2;
extern lv_obj_t * ui_droplets2;
void ui_event_getseed2(lv_event_t * e);
extern lv_obj_t * ui_getseed2;
void ui_event_plantstagetextarea2(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea2;
void ui_event_plant2(lv_event_t * e);
extern lv_obj_t * ui_plant2;
extern lv_obj_t * ui_plantimg2;
extern lv_obj_t * ui_plantlabel2;
extern lv_obj_t * ui_achivevment2;
void ui_event_achivevmentimage2(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage2;
extern lv_obj_t * ui_achivevmentlabel2;
extern lv_obj_t * ui_growthstage1;
extern lv_obj_t * ui_growthstageimage2;
void ui_event_growthstagelabel2(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel2;
void ui_event_back1(lv_event_t * e);
extern lv_obj_t * ui_back1;
extern lv_obj_t * ui_tomato1;
void ui_event_tomato2(lv_event_t * e);
extern lv_obj_t * ui_tomato2;
void ui_event_tomato3(lv_event_t * e);
extern lv_obj_t * ui_tomato3;
void ui_event_tomato4(lv_event_t * e);
extern lv_obj_t * ui_tomato4;
void ui_event_tomato5(lv_event_t * e);
extern lv_obj_t * ui_tomato5;
void ui_event_tomato6(lv_event_t * e);
extern lv_obj_t * ui_tomato6;
void ui_event_tomato7(lv_event_t * e);
extern lv_obj_t * ui_tomato7;
extern lv_obj_t * ui_message2;
void ui_event_Label9(lv_event_t * e);
extern lv_obj_t * ui_Label9;
// SCREEN: ui_cactusscreen
void ui_cactusscreen_screen_init(void);
extern lv_obj_t * ui_cactusscreen;
extern lv_obj_t * ui_background3;
void ui_event_Insectremoval3(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval3;
void ui_event_fertilize3(lv_event_t * e);
extern lv_obj_t * ui_fertilize3;
void ui_event_watering3(lv_event_t * e);
extern lv_obj_t * ui_watering3;
extern lv_obj_t * ui_health3;
void ui_event_healthlabel3(lv_event_t * e);
extern lv_obj_t * ui_healthlabel3;
extern lv_obj_t * ui_healthImage3;
extern lv_obj_t * ui_state3;
void ui_event_statelabel3(lv_event_t * e);
extern lv_obj_t * ui_statelabel3;
extern lv_obj_t * ui_stateImage3;
extern lv_obj_t * ui_humidity3;
void ui_event_humiditylabel3(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel3;
extern lv_obj_t * ui_humidityImage3;
extern lv_obj_t * ui_temperature3;
void ui_event_temperaturelabel3(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel3;
extern lv_obj_t * ui_temperatureImage3;
extern lv_obj_t * ui_light3;
void ui_event_lightlabel3(lv_event_t * e);
extern lv_obj_t * ui_lightlabel3;
extern lv_obj_t * ui_lightImage3;
extern lv_obj_t * ui_weather3;
void ui_event_weatherlabel3(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel3;
extern lv_obj_t * ui_weatherimage3;
extern lv_obj_t * ui_season3;
extern lv_obj_t * ui_seasonimage3;
void ui_event_seasonlabel3(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel3;
void ui_event_Illustrated3(lv_event_t * e);
extern lv_obj_t * ui_Illustrated3;
void ui_event_next3(lv_event_t * e);
extern lv_obj_t * ui_next3;
extern lv_obj_t * ui_droplets3;
void ui_event_getseed3(lv_event_t * e);
extern lv_obj_t * ui_getseed3;
void ui_event_plantstagetextarea3(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea3;
void ui_event_plant3(lv_event_t * e);
extern lv_obj_t * ui_plant3;
extern lv_obj_t * ui_plantimg3;
extern lv_obj_t * ui_plantlabel3;
extern lv_obj_t * ui_achivevment3;
void ui_event_achivevmentimage3(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage3;
extern lv_obj_t * ui_achivevmentlabel3;
extern lv_obj_t * ui_growthstage2;
extern lv_obj_t * ui_growthstageimage3;
void ui_event_growthstagelabel3(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel3;
void ui_event_back2(lv_event_t * e);
extern lv_obj_t * ui_back2;
extern lv_obj_t * ui_Cactus1;
void ui_event_Cactus2(lv_event_t * e);
extern lv_obj_t * ui_Cactus2;
void ui_event_Cactus3(lv_event_t * e);
extern lv_obj_t * ui_Cactus3;
void ui_event_Cactus4(lv_event_t * e);
extern lv_obj_t * ui_Cactus4;
void ui_event_Cactus5(lv_event_t * e);
extern lv_obj_t * ui_Cactus5;
void ui_event_Cactus6(lv_event_t * e);
extern lv_obj_t * ui_Cactus6;
void ui_event_Cactus7(lv_event_t * e);
extern lv_obj_t * ui_Cactus7;
extern lv_obj_t * ui_message3;
void ui_event_Label10(lv_event_t * e);
extern lv_obj_t * ui_Label10;
// SCREEN: ui_cannibalscreen
void ui_cannibalscreen_screen_init(void);
void ui_event_cannibalscreen(lv_event_t * e);
extern lv_obj_t * ui_cannibalscreen;
extern lv_obj_t * ui_background4;
void ui_event_Insectremoval4(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval4;
void ui_event_fertilize4(lv_event_t * e);
extern lv_obj_t * ui_fertilize4;
void ui_event_watering4(lv_event_t * e);
extern lv_obj_t * ui_watering4;
extern lv_obj_t * ui_health4;
void ui_event_healthlabel4(lv_event_t * e);
extern lv_obj_t * ui_healthlabel4;
extern lv_obj_t * ui_healthImage4;
extern lv_obj_t * ui_state4;
void ui_event_statelabel4(lv_event_t * e);
extern lv_obj_t * ui_statelabel4;
extern lv_obj_t * ui_stateImage4;
extern lv_obj_t * ui_humidity4;
void ui_event_humiditylabel4(lv_event_t * e);
extern lv_obj_t * ui_humiditylabel4;
extern lv_obj_t * ui_humidityImage4;
extern lv_obj_t * ui_temperature4;
void ui_event_temperaturelabel4(lv_event_t * e);
extern lv_obj_t * ui_temperaturelabel4;
extern lv_obj_t * ui_temperatureImage4;
extern lv_obj_t * ui_light4;
void ui_event_lightlabel4(lv_event_t * e);
extern lv_obj_t * ui_lightlabel4;
extern lv_obj_t * ui_lightImage4;
extern lv_obj_t * ui_weather4;
void ui_event_weatherlabel4(lv_event_t * e);
extern lv_obj_t * ui_weatherlabel4;
extern lv_obj_t * ui_weatherimage4;
extern lv_obj_t * ui_season4;
extern lv_obj_t * ui_seasonimage4;
void ui_event_seasonlabel4(lv_event_t * e);
extern lv_obj_t * ui_seasonlabel4;
void ui_event_Illustrated4(lv_event_t * e);
extern lv_obj_t * ui_Illustrated4;
extern lv_obj_t * ui_next4;
extern lv_obj_t * ui_droplets4;
void ui_event_getseed4(lv_event_t * e);
extern lv_obj_t * ui_getseed4;
void ui_event_plantstagetextarea4(lv_event_t * e);
extern lv_obj_t * ui_plantstagetextarea4;
void ui_event_plant4(lv_event_t * e);
extern lv_obj_t * ui_plant4;
extern lv_obj_t * ui_plantimg4;
extern lv_obj_t * ui_plantlabel4;
extern lv_obj_t * ui_achivevment4;
void ui_event_achivevmentimage4(lv_event_t * e);
extern lv_obj_t * ui_achivevmentimage4;
extern lv_obj_t * ui_achivevmentlabel4;
extern lv_obj_t * ui_growthstage3;
extern lv_obj_t * ui_growthstageimage4;
void ui_event_growthstagelabel4(lv_event_t * e);
extern lv_obj_t * ui_growthstagelabel4;
void ui_event_back3(lv_event_t * e);
extern lv_obj_t * ui_back3;
extern lv_obj_t * ui_Cannibal1;
void ui_event_Cannibal2(lv_event_t * e);
extern lv_obj_t * ui_Cannibal2;
void ui_event_Cannibal3(lv_event_t * e);
extern lv_obj_t * ui_Cannibal3;
void ui_event_Cannibal4(lv_event_t * e);
extern lv_obj_t * ui_Cannibal4;
void ui_event_Cannibal5(lv_event_t * e);
extern lv_obj_t * ui_Cannibal5;
void ui_event_Cannibal6(lv_event_t * e);
extern lv_obj_t * ui_Cannibal6;
void ui_event_Cannibal7(lv_event_t * e);
extern lv_obj_t * ui_Cannibal7;
extern lv_obj_t * ui_message4;
void ui_event_Label11(lv_event_t * e);
extern lv_obj_t * ui_Label11;
// SCREEN: ui_mainscreen
void ui_mainscreen_screen_init(void);
extern lv_obj_t * ui_mainscreen;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label16;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label17;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label18;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label19;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui____initial_actions0;

void illu_change(lv_event_t * e);

LV_IMG_DECLARE(ui_img_background_png);
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_876520695);    // assets/盆栽植物_1749862881.png
LV_IMG_DECLARE(ui_img_1224826616);    // assets/大风.png
LV_IMG_DECLARE(ui_img_inventory_png);    // assets/Inventory.png
LV_IMG_DECLARE(ui_img_bug_spray_png);    // assets/bug_spray.png
LV_IMG_DECLARE(ui_img_treefood_png);    // assets/TreeFood.png
LV_IMG_DECLARE(ui_img_wateringcan_png);    // assets/WateringCan.png
LV_IMG_DECLARE(ui_img_561135566);    // assets/红色爱心_1749806193.png
LV_IMG_DECLARE(ui_img_projectile_star_png);    // assets/Projectile_star.png
LV_IMG_DECLARE(ui_img_waterdrop_png);    // assets/waterdrop.png
LV_IMG_DECLARE(ui_img_1795366294);    // assets/温度计_1749799392.png
LV_IMG_DECLARE(ui_img_1138793207);    // assets/光照.png
LV_IMG_DECLARE(ui_img_1606731336);    // assets/袜子_1749805859.png
LV_IMG_DECLARE(ui_img_683165229);    // assets/盛开的花朵_1749806018.png
LV_IMG_DECLARE(ui_img_178160675);    // assets/卷轴与毛笔_1749798033.png
LV_IMG_DECLARE(ui_img_zen_nextgarden_png);    // assets/Zen_NextGarden.png
LV_IMG_DECLARE(ui_img_354690767);    // assets/水滴_1749819882.png
LV_IMG_DECLARE(ui_img_1745983305);    // assets/园艺师_1749865266.png
LV_IMG_DECLARE(ui_img_403432398);    // assets/个人成就.png
LV_IMG_DECLARE(ui_img_577302902);    // assets/妙蛙种子.png
LV_IMG_DECLARE(ui_img_1692171843);    // assets/向日葵1.png
LV_IMG_DECLARE(ui_img_1692168768);    // assets/向日葵2.png
LV_IMG_DECLARE(ui_img_1692169793);    // assets/向日葵3.png
LV_IMG_DECLARE(ui_img_1692175166);    // assets/向日葵4.png
LV_IMG_DECLARE(ui_img_1692176191);    // assets/向日葵5.png
LV_IMG_DECLARE(ui_img_1692173116);    // assets/向日葵6.png
LV_IMG_DECLARE(ui_img_1692174141);    // assets/向日葵7.png
LV_IMG_DECLARE(ui_img_1083307527);    // assets/对话框.png
LV_IMG_DECLARE(ui_img_zen_prevgarden_png);    // assets/Zen_PrevGarden.png
LV_IMG_DECLARE(ui_img_letterbg__png);    // assets/letterBG..png
LV_IMG_DECLARE(ui_img_uppercaveplants__png);    // assets/upperCavePlants..png
LV_IMG_DECLARE(ui_img_sunflower_png);    // assets/sunflower.png
LV_IMG_DECLARE(ui_img_grass__png);    // assets/grass..png
LV_IMG_DECLARE(ui_img_hoedirtsnow__png);    // assets/hoeDirtSnow..png
LV_IMG_DECLARE(ui_img_hoedirt1_png);    // assets/hoeDirt1.png
LV_IMG_DECLARE(ui_img_405436818);    // assets/西红柿7.png
LV_IMG_DECLARE(ui_img_1437470208);    // assets/仙人掌6.png
LV_IMG_DECLARE(ui_img_cannibal7_png);    // assets/Cannibal7.png
LV_IMG_DECLARE(ui_img_901739709);    // assets/货币.png
LV_IMG_DECLARE(ui_img_405426072);    // assets/西红柿1.png
LV_IMG_DECLARE(ui_img_405431445);    // assets/西红柿2.png
LV_IMG_DECLARE(ui_img_405432470);    // assets/西红柿3.png
LV_IMG_DECLARE(ui_img_405437843);    // assets/西红柿4.png
LV_IMG_DECLARE(ui_img_405430420);    // assets/西红柿5.png
LV_IMG_DECLARE(ui_img_405435793);    // assets/西红柿6.png
LV_IMG_DECLARE(ui_img_1437479929);    // assets/仙人掌1.png
LV_IMG_DECLARE(ui_img_1437474556);    // assets/仙人掌2.png
LV_IMG_DECLARE(ui_img_1437473531);    // assets/仙人掌3.png
LV_IMG_DECLARE(ui_img_1437468158);    // assets/仙人掌4.png
LV_IMG_DECLARE(ui_img_1437475581);    // assets/仙人掌5.png
LV_IMG_DECLARE(ui_img_1437469183);    // assets/仙人掌7.png
LV_IMG_DECLARE(ui_img_cannibal1_png);    // assets/Cannibal1.png
LV_IMG_DECLARE(ui_img_cannibal2_png);    // assets/Cannibal2.png
LV_IMG_DECLARE(ui_img_cannibal3_png);    // assets/Cannibal3.png
LV_IMG_DECLARE(ui_img_cannibal4_png);    // assets/Cannibal4.png
LV_IMG_DECLARE(ui_img_cannibal5_png);    // assets/Cannibal5.png
LV_IMG_DECLARE(ui_img_cannibal6_png);    // assets/Cannibal6.png
LV_IMG_DECLARE(ui_img_flowering1_png);    // assets/flowering1.png
LV_IMG_DECLARE(ui_img_fruittrees1_png);    // assets/fruitTrees1.png
LV_IMG_DECLARE(ui_img_fruittrees2_png);    // assets/fruitTrees2.png
LV_IMG_DECLARE(ui_img_348401948);    // assets/萌芽_1749865223.png


LV_IMG_DECLARE(ui_img_145349238); //下雨
LV_IMG_DECLARE(ui_img_145351288); //下雪
LV_IMG_DECLARE(ui_img_1664587152);//晴朗
LV_IMG_DECLARE(ui_img_1772208564);//多云


LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
