// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_cannibalscreen_screen_init(void)
{
    ui_cannibalscreen = lv_obj_create(NULL);
    lv_obj_set_user_data(ui_cannibalscreen, "ui_cannibalscreen");
    lv_obj_clear_flag(ui_cannibalscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_cannibalscreen, &ui_img_1664587152, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_cannibalscreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_background4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_background4, &ui_img_inventory_png);
    lv_obj_set_width(ui_background4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_background4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_background4, 2);
    lv_obj_set_y(ui_background4, 14);
    lv_obj_set_align(ui_background4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_background4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Insectremoval4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Insectremoval4, &ui_img_bug_spray_png);
    lv_obj_set_width(ui_Insectremoval4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Insectremoval4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Insectremoval4, -245);
    lv_obj_set_y(ui_Insectremoval4, 181);
    lv_obj_set_align(ui_Insectremoval4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Insectremoval4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Insectremoval4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Insectremoval4, 150);

    ui_fertilize4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_fertilize4, &ui_img_treefood_png);
    lv_obj_set_width(ui_fertilize4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fertilize4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fertilize4, -304);
    lv_obj_set_y(ui_fertilize4, 179);
    lv_obj_set_align(ui_fertilize4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fertilize4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fertilize4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_fertilize4, 150);

    ui_watering4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_watering4, &ui_img_wateringcan_png);
    lv_obj_set_width(ui_watering4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watering4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watering4, -365);
    lv_obj_set_y(ui_watering4, 176);
    lv_obj_set_align(ui_watering4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watering4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_watering4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_watering4, 180);

    ui_health4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_health4);
    lv_obj_set_width(ui_health4, 281);
    lv_obj_set_height(ui_health4, 45);
    lv_obj_set_x(ui_health4, -250);
    lv_obj_set_y(ui_health4, 0);
    lv_obj_set_align(ui_health4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_health4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_healthlabel4 = lv_label_create(ui_health4);
    lv_obj_set_width(ui_healthlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_healthlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_healthlabel4, -28);
    lv_obj_set_y(ui_healthlabel4, 7);
    lv_obj_set_align(ui_healthlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_healthlabel4, "健康");
    lv_obj_set_style_text_font(ui_healthlabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_healthImage4 = lv_img_create(ui_health4);
    lv_img_set_src(ui_healthImage4, &ui_img_561135566);
    lv_obj_set_width(ui_healthImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_healthImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_healthImage4, -93);
    lv_obj_set_y(ui_healthImage4, -1);
    lv_obj_set_align(ui_healthImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_healthImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_healthImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_healthImage4, 150);

    ui_state4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_state4);
    lv_obj_set_width(ui_state4, 229);
    lv_obj_set_height(ui_state4, 56);
    lv_obj_set_x(ui_state4, -283);
    lv_obj_set_y(ui_state4, 59);
    lv_obj_set_align(ui_state4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_state4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_statelabel4 = lv_label_create(ui_state4);
    lv_obj_set_width(ui_statelabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statelabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statelabel4, 6);
    lv_obj_set_y(ui_statelabel4, 5);
    lv_obj_set_align(ui_statelabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statelabel4, "年龄");
    lv_obj_set_style_text_font(ui_statelabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stateImage4 = lv_img_create(ui_state4);
    lv_img_set_src(ui_stateImage4, &ui_img_projectile_star_png);
    lv_obj_set_width(ui_stateImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stateImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stateImage4, -59);
    lv_obj_set_y(ui_stateImage4, -2);
    lv_obj_set_align(ui_stateImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stateImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stateImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_stateImage4, 400);

    ui_humidity4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_humidity4);
    lv_obj_set_width(ui_humidity4, 207);
    lv_obj_set_height(ui_humidity4, 48);
    lv_obj_set_x(ui_humidity4, 292);
    lv_obj_set_y(ui_humidity4, -60);
    lv_obj_set_align(ui_humidity4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humidity4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humiditylabel4 = lv_label_create(ui_humidity4);
    lv_obj_set_width(ui_humiditylabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiditylabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiditylabel4, -15);
    lv_obj_set_y(ui_humiditylabel4, 9);
    lv_obj_set_align(ui_humiditylabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humiditylabel4, "湿度");
    lv_obj_set_style_text_font(ui_humiditylabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidityImage4 = lv_img_create(ui_humidity4);
    lv_img_set_src(ui_humidityImage4, &ui_img_waterdrop_png);
    lv_obj_set_width(ui_humidityImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidityImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidityImage4, -76);
    lv_obj_set_y(ui_humidityImage4, 0);
    lv_obj_set_align(ui_humidityImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidityImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humidityImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humidityImage4, 400);

    ui_temperature4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_temperature4);
    lv_obj_set_width(ui_temperature4, 204);
    lv_obj_set_height(ui_temperature4, 46);
    lv_obj_set_x(ui_temperature4, 294);
    lv_obj_set_y(ui_temperature4, 57);
    lv_obj_set_align(ui_temperature4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temperature4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperaturelabel4 = lv_label_create(ui_temperature4);
    lv_obj_set_width(ui_temperaturelabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturelabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturelabel4, -16);
    lv_obj_set_y(ui_temperaturelabel4, 7);
    lv_obj_set_align(ui_temperaturelabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperaturelabel4, "温度");
    lv_obj_set_style_text_font(ui_temperaturelabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperatureImage4 = lv_img_create(ui_temperature4);
    lv_img_set_src(ui_temperatureImage4, &ui_img_1795366294);
    lv_obj_set_width(ui_temperatureImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperatureImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperatureImage4, -77);
    lv_obj_set_y(ui_temperatureImage4, -3);
    lv_obj_set_align(ui_temperatureImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temperatureImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperatureImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_temperatureImage4, 180);

    ui_light4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_light4);
    lv_obj_set_width(ui_light4, 210);
    lv_obj_set_height(ui_light4, 53);
    lv_obj_set_x(ui_light4, 292);
    lv_obj_set_y(ui_light4, -2);
    lv_obj_set_align(ui_light4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_light4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lightlabel4 = lv_label_create(ui_light4);
    lv_obj_set_width(ui_lightlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightlabel4, -14);
    lv_obj_set_y(ui_lightlabel4, 6);
    lv_obj_set_align(ui_lightlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightlabel4, "光照");
    lv_obj_set_style_text_font(ui_lightlabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightImage4 = lv_img_create(ui_light4);
    lv_img_set_src(ui_lightImage4, &ui_img_1138793207);
    lv_obj_set_width(ui_lightImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightImage4, -74);
    lv_obj_set_y(ui_lightImage4, -2);
    lv_obj_set_align(ui_lightImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lightImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lightImage4, 170);

    ui_weather4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_weather4);
    lv_obj_set_width(ui_weather4, 167);
    lv_obj_set_height(ui_weather4, 64);
    lv_obj_set_x(ui_weather4, -134);
    lv_obj_set_y(ui_weather4, -199);
    lv_obj_set_align(ui_weather4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherlabel4 = lv_label_create(ui_weather4);
    lv_obj_set_width(ui_weatherlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherlabel4, 8);
    lv_obj_set_y(ui_weatherlabel4, 1);
    lv_obj_set_align(ui_weatherlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherlabel4, "天气");
    lv_obj_set_style_text_font(ui_weatherlabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherimage4 = lv_img_create(ui_weather4);
    lv_img_set_src(ui_weatherimage4, &ui_img_1606731336);
    lv_obj_set_width(ui_weatherimage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherimage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherimage4, -37);
    lv_obj_set_y(ui_weatherimage4, -5);
    lv_obj_set_align(ui_weatherimage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherimage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weatherimage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_season4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_season4);
    lv_obj_set_width(ui_season4, 134);
    lv_obj_set_height(ui_season4, 63);
    lv_obj_set_x(ui_season4, 15);
    lv_obj_set_y(ui_season4, -204);
    lv_obj_set_align(ui_season4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_season4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seasonimage4 = lv_img_create(ui_season4);
    lv_img_set_src(ui_seasonimage4, &ui_img_683165229);
    lv_obj_set_width(ui_seasonimage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seasonimage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seasonimage4, -27);
    lv_obj_set_y(ui_seasonimage4, -1);
    lv_obj_set_align(ui_seasonimage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seasonimage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seasonimage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seasonimage4, 220);

    ui_seasonlabel4 = lv_label_create(ui_season4);
    lv_obj_set_width(ui_seasonlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seasonlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seasonlabel4, 29);
    lv_obj_set_y(ui_seasonlabel4, 7);
    lv_obj_set_align(ui_seasonlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_seasonlabel4, "春天");
    lv_obj_set_style_text_font(ui_seasonlabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Illustrated4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Illustrated4, &ui_img_178160675);
    lv_obj_set_width(ui_Illustrated4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Illustrated4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Illustrated4, 358);
    lv_obj_set_y(ui_Illustrated4, 181);
    lv_obj_set_align(ui_Illustrated4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Illustrated4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Illustrated4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Illustrated4, 240);

    ui_next4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_next4, &ui_img_zen_nextgarden_png);
    lv_obj_set_width(ui_next4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_next4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_next4, 360);
    lv_obj_set_y(ui_next4, 184);
    lv_obj_set_align(ui_next4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_next4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_next4, 200);

    ui_droplets4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_droplets4, &ui_img_354690767);
    lv_obj_set_width(ui_droplets4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_droplets4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_droplets4, 82);
    lv_obj_set_y(ui_droplets4, 7);
    lv_obj_set_align(ui_droplets4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_droplets4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_droplets4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_droplets4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_getseed4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_getseed4, &ui_img_876520695);
    lv_obj_set_width(ui_getseed4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_getseed4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_getseed4, 294);
    lv_obj_set_y(ui_getseed4, 178);
    lv_obj_set_align(ui_getseed4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_getseed4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_getseed4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantstagetextarea4 = lv_textarea_create(ui_cannibalscreen);
    lv_obj_set_width(ui_plantstagetextarea4, 184);
    lv_obj_set_height(ui_plantstagetextarea4, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_plantstagetextarea4, -12);
    lv_obj_set_y(ui_plantstagetextarea4, -76);
    lv_obj_set_align(ui_plantstagetextarea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_plantstagetextarea4, "Placeholder...");
    lv_textarea_set_one_line(ui_plantstagetextarea4, true);
    lv_obj_add_flag(ui_plantstagetextarea4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_plantstagetextarea4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_plantstagetextarea4, lv_color_hex(0xB7C16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_plantstagetextarea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_plantstagetextarea4, LV_BLEND_MODE_NORMAL, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_plantstagetextarea4, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_plant4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_plant4);
    lv_obj_set_width(ui_plant4, 87);
    lv_obj_set_height(ui_plant4, 45);
    lv_obj_set_x(ui_plant4, -343);
    lv_obj_set_y(ui_plant4, -207);
    lv_obj_set_align(ui_plant4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_plant4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantimg4 = lv_img_create(ui_plant4);
    lv_img_set_src(ui_plantimg4, &ui_img_1745983305);
    lv_obj_set_width(ui_plantimg4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plantimg4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plantimg4, -22);
    lv_obj_set_y(ui_plantimg4, -6);
    lv_obj_set_align(ui_plantimg4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_plantimg4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_plantimg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_plantlabel4 = lv_label_create(ui_plant4);
    lv_obj_set_width(ui_plantlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plantlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plantlabel4, 17);
    lv_obj_set_y(ui_plantlabel4, 3);
    lv_obj_set_align(ui_plantlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plantlabel4, "种植");
    lv_obj_set_style_text_font(ui_plantlabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_achivevment4 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_achivevment4);
    lv_obj_set_width(ui_achivevment4, 84);
    lv_obj_set_height(ui_achivevment4, 77);
    lv_obj_set_x(ui_achivevment4, 346);
    lv_obj_set_y(ui_achivevment4, -133);
    lv_obj_set_align(ui_achivevment4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_achivevment4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_achivevmentimage4 = lv_img_create(ui_achivevment4);
    lv_img_set_src(ui_achivevmentimage4, &ui_img_403432398);
    lv_obj_set_width(ui_achivevmentimage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_achivevmentimage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_achivevmentimage4, -4);
    lv_obj_set_y(ui_achivevmentimage4, -10);
    lv_obj_set_align(ui_achivevmentimage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_achivevmentimage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_achivevmentimage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_achivevmentlabel4 = lv_label_create(ui_achivevment4);
    lv_obj_set_width(ui_achivevmentlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_achivevmentlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_achivevmentlabel4, -4);
    lv_obj_set_y(ui_achivevmentlabel4, 23);
    lv_obj_set_align(ui_achivevmentlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_achivevmentlabel4, "成就");
    lv_obj_set_style_text_font(ui_achivevmentlabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_growthstage3 = lv_obj_create(ui_cannibalscreen);
    lv_obj_remove_style_all(ui_growthstage3);
    lv_obj_set_width(ui_growthstage3, 197);
    lv_obj_set_height(ui_growthstage3, 89);
    lv_obj_set_x(ui_growthstage3, -295);
    lv_obj_set_y(ui_growthstage3, -58);
    lv_obj_set_align(ui_growthstage3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_growthstage3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_growthstageimage4 = lv_img_create(ui_growthstage3);
    lv_img_set_src(ui_growthstageimage4, &ui_img_577302902);
    lv_obj_set_width(ui_growthstageimage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_growthstageimage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_growthstageimage4, -45);
    lv_obj_set_y(ui_growthstageimage4, -1);
    lv_obj_set_align(ui_growthstageimage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_growthstageimage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_growthstageimage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_growthstagelabel4 = lv_label_create(ui_growthstage3);
    lv_obj_set_width(ui_growthstagelabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_growthstagelabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_growthstagelabel4, 19);
    lv_obj_set_y(ui_growthstagelabel4, 7);
    lv_obj_set_align(ui_growthstagelabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_growthstagelabel4, "种子");
    lv_obj_set_style_text_font(ui_growthstagelabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back3 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_back3, &ui_img_zen_prevgarden_png);
    lv_obj_set_width(ui_back3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_back3, 228);
    lv_obj_set_y(ui_back3, 179);
    lv_obj_set_align(ui_back3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_back3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cannibal1 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal1, &ui_img_cannibal1_png);
    lv_obj_set_width(ui_Cannibal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal1, -4);
    lv_obj_set_y(ui_Cannibal1, 146);
    lv_obj_set_align(ui_Cannibal1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Cannibal1, 80);

    ui_Cannibal2 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal2, &ui_img_cannibal2_png);
    lv_obj_set_width(ui_Cannibal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal2, -9);
    lv_obj_set_y(ui_Cannibal2, 132);
    lv_obj_set_align(ui_Cannibal2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cannibal3 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal3, &ui_img_cannibal3_png);
    lv_obj_set_width(ui_Cannibal3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal3, -10);
    lv_obj_set_y(ui_Cannibal3, 123);
    lv_obj_set_align(ui_Cannibal3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cannibal4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal4, &ui_img_cannibal4_png);
    lv_obj_set_width(ui_Cannibal4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal4, -10);
    lv_obj_set_y(ui_Cannibal4, 106);
    lv_obj_set_align(ui_Cannibal4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cannibal5 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal5, &ui_img_cannibal5_png);
    lv_obj_set_width(ui_Cannibal5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal5, -10);
    lv_obj_set_y(ui_Cannibal5, 104);
    lv_obj_set_align(ui_Cannibal5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cannibal6 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal6, &ui_img_cannibal6_png);
    lv_obj_set_width(ui_Cannibal6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal6, -8);
    lv_obj_set_y(ui_Cannibal6, 120);
    lv_obj_set_align(ui_Cannibal6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Cannibal7 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_Cannibal7, &ui_img_cannibal7_png);
    lv_obj_set_width(ui_Cannibal7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cannibal7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cannibal7, -9);
    lv_obj_set_y(ui_Cannibal7, 113);
    lv_obj_set_align(ui_Cannibal7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cannibal7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cannibal7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Cannibal7, 400);

    ui_message4 = lv_img_create(ui_cannibalscreen);
    lv_img_set_src(ui_message4, &ui_img_1083307527);
    lv_obj_set_width(ui_message4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_message4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_message4, 203);
    lv_obj_set_y(ui_message4, -129);
    lv_obj_set_align(ui_message4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_message4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_message4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_message4, 300);

    ui_Label11 = lv_label_create(ui_message4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 2);
    lv_obj_set_y(ui_Label11, -10);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "3333333333333");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Insectremoval4, ui_event_Insectremoval4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fertilize4, ui_event_fertilize4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watering4, ui_event_watering4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_healthlabel4, ui_event_healthlabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statelabel4, ui_event_statelabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_humiditylabel4, ui_event_humiditylabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temperaturelabel4, ui_event_temperaturelabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightlabel4, ui_event_lightlabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weatherlabel4, ui_event_weatherlabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seasonlabel4, ui_event_seasonlabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Illustrated4, ui_event_Illustrated4, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_getseed4, ui_event_getseed4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plantstagetextarea4, ui_event_plantstagetextarea4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plant4, ui_event_plant4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_achivevmentimage4, ui_event_achivevmentimage4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_growthstagelabel4, ui_event_growthstagelabel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_back3, ui_event_back3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cannibal2, ui_event_Cannibal2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cannibal3, ui_event_Cannibal3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cannibal4, ui_event_Cannibal4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cannibal5, ui_event_Cannibal5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cannibal6, ui_event_Cannibal6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cannibal7, ui_event_Cannibal7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label11, ui_event_Label11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cannibalscreen, ui_event_cannibalscreen, LV_EVENT_ALL, NULL);

}
