// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_initscreen.h"
#include "screens/ui_sunflowerscreen.h"
#include "screens/ui_IllustratedScreen.h"
#include "screens/ui_storeScreen.h"
#include "screens/ui_tomatoscreen.h"
#include "screens/ui_cactusscreen.h"
#include "screens/ui_cannibalscreen.h"
#include "screens/ui_mainscreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * wateringmove1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * imageangle1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wateringback1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Opacityfull1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Opacityzero1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fertilizemove1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fertilizeback1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Insectremovalmove1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Insectremovalback1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * plantstate_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_876520695);    // assets/盆栽植物_1749862881.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/cloudy.png
LV_IMG_DECLARE(ui_img_inventory_png);    // assets/Inventory.png
LV_IMG_DECLARE(ui_img_bug_spray_png);    // assets/bug_spray.png
LV_IMG_DECLARE(ui_img_treefood_png);    // assets/TreeFood.png
LV_IMG_DECLARE(ui_img_wateringcan_png);    // assets/WateringCan.png
LV_IMG_DECLARE(ui_img_561135566);    // assets/红色爱心_1749806193.png
LV_IMG_DECLARE(ui_img_projectile_star_png);    // assets/Projectile_star.png
LV_IMG_DECLARE(ui_img_waterdrop_png);    // assets/waterdrop.png
LV_IMG_DECLARE(ui_img_1795366294);    // assets/温度计_1749799392.png
LV_IMG_DECLARE(ui_img_1138793207);    // assets/光照.png
LV_IMG_DECLARE(ui_img_1606731336);    // assets/袜子_1749805859.png
LV_IMG_DECLARE(ui_img_683165229);    // assets/盛开的花朵_1749806018.png
LV_IMG_DECLARE(ui_img_178160675);    // assets/卷轴与毛笔_1749798033.png
LV_IMG_DECLARE(ui_img_zen_nextgarden_png);    // assets/Zen_NextGarden.png
LV_IMG_DECLARE(ui_img_354690767);    // assets/水滴_1749819882.png
LV_IMG_DECLARE(ui_img_1745983305);    // assets/园艺师_1749865266.png
LV_IMG_DECLARE(ui_img_403432398);    // assets/个人成就.png
LV_IMG_DECLARE(ui_img_577302902);    // assets/妙蛙种子.png
LV_IMG_DECLARE(ui_img_sunflower1_png);    // assets/sunflower1.png
LV_IMG_DECLARE(ui_img_sunflower2_png);    // assets/sunflower2.png
LV_IMG_DECLARE(ui_img_sunflower3_png);    // assets/sunflower3.png
LV_IMG_DECLARE(ui_img_sunflower4_png);    // assets/sunflower4.png
LV_IMG_DECLARE(ui_img_sunflower5_png);    // assets/sunflower5.png
LV_IMG_DECLARE(ui_img_sunflower6_png);    // assets/sunflower6.png
LV_IMG_DECLARE(ui_img_sunflower7_png);    // assets/sunflower7.png
LV_IMG_DECLARE(ui_img_1083307527);    // assets/对话框.png
LV_IMG_DECLARE(ui_img_zen_prevgarden_png);    // assets/Zen_PrevGarden.png
LV_IMG_DECLARE(ui_img_letterbg__png);    // assets/letterBG..png
LV_IMG_DECLARE(ui_img_uppercaveplants__png);    // assets/upperCavePlants..png
LV_IMG_DECLARE(ui_img_sunflower_png);    // assets/sunflower.png
LV_IMG_DECLARE(ui_img_grass__png);    // assets/grass..png
LV_IMG_DECLARE(ui_img_hoedirtsnow__png);    // assets/hoeDirtSnow..png
LV_IMG_DECLARE(ui_img_hoedirt1_png);    // assets/hoeDirt1.png
LV_IMG_DECLARE(ui_img_tomato7_png);    // assets/tomato7.png
LV_IMG_DECLARE(ui_img_cacuts7_png);    // assets/cacuts7.png
LV_IMG_DECLARE(ui_img_cannibal7_png);    // assets/Cannibal7.png
LV_IMG_DECLARE(ui_img_901739709);    // assets/货币.png
LV_IMG_DECLARE(ui_img_rainy_png);    // assets/rainy.png
LV_IMG_DECLARE(ui_img_tomato1_png);    // assets/tomato1.png
LV_IMG_DECLARE(ui_img_tomato2_png);    // assets/tomato2.png
LV_IMG_DECLARE(ui_img_tomato3_png);    // assets/tomato3.png
LV_IMG_DECLARE(ui_img_tomato4_png);    // assets/tomato4.png
LV_IMG_DECLARE(ui_img_tomato5_png);    // assets/tomato5.png
LV_IMG_DECLARE(ui_img_tomato6_png);    // assets/tomato6.png
LV_IMG_DECLARE(ui_img_snowy_png);    // assets/snowy.png
LV_IMG_DECLARE(ui_img_cacuts1_png);    // assets/cacuts1.png
LV_IMG_DECLARE(ui_img_cacuts2_png);    // assets/cacuts2.png
LV_IMG_DECLARE(ui_img_cacuts3_png);    // assets/cacuts3.png
LV_IMG_DECLARE(ui_img_cacuts4_png);    // assets/cacuts4.png
LV_IMG_DECLARE(ui_img_cacuts5_png);    // assets/cacuts5.png
LV_IMG_DECLARE(ui_img_cacuts6_png);    // assets/cacuts6.png
LV_IMG_DECLARE(ui_img_windy_png);    // assets/windy.png
LV_IMG_DECLARE(ui_img_cannibal1_png);    // assets/Cannibal1.png
LV_IMG_DECLARE(ui_img_cannibal2_png);    // assets/Cannibal2.png
LV_IMG_DECLARE(ui_img_cannibal3_png);    // assets/Cannibal3.png
LV_IMG_DECLARE(ui_img_cannibal4_png);    // assets/Cannibal4.png
LV_IMG_DECLARE(ui_img_cannibal5_png);    // assets/Cannibal5.png
LV_IMG_DECLARE(ui_img_cannibal6_png);    // assets/Cannibal6.png
LV_IMG_DECLARE(ui_img_clear_png);    // assets/clear.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
