// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void wateringmove1_Animation(lv_obj_t * TargetObject, int delay);
void imageangle1_Animation(lv_obj_t * TargetObject, int delay);
void wateringback1_Animation(lv_obj_t * TargetObject, int delay);
void Opacityfull1_Animation(lv_obj_t * TargetObject, int delay);
void Opacityzero1_Animation(lv_obj_t * TargetObject, int delay);
void fertilizemove1_Animation(lv_obj_t * TargetObject, int delay);
void fertilizeback1_Animation(lv_obj_t * TargetObject, int delay);
void Insectremovalmove1_Animation(lv_obj_t * TargetObject, int delay);
void Insectremovalback1_Animation(lv_obj_t * TargetObject, int delay);
void plantstate_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_initscreen
void ui_initscreen_screen_init(void);
extern lv_obj_t * ui_initscreen;
extern lv_obj_t * ui_Label1;
void ui_event_getseedinit(lv_event_t * e);
extern lv_obj_t * ui_getseedinit;
extern lv_obj_t * ui_getseedlabelinit;
extern lv_obj_t * ui_getseedimginit;
// SCREEN: ui_firstscreen
void ui_firstscreen_screen_init(void);
extern lv_obj_t * ui_firstscreen;
void ui_event_Insectremoval1(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval1;
void ui_event_fertilize1(lv_event_t * e);
extern lv_obj_t * ui_fertilize1;
void ui_event_watering1(lv_event_t * e);
extern lv_obj_t * ui_watering1;
extern lv_obj_t * ui_health1;
extern lv_obj_t * ui_healthlabel1;
extern lv_obj_t * ui_healthImage1;
extern lv_obj_t * ui_state1;
extern lv_obj_t * ui_statelabel1;
extern lv_obj_t * ui_stateImage1;
extern lv_obj_t * ui_humidity1;
extern lv_obj_t * ui_humiditylabel1;
extern lv_obj_t * ui_humidityImage1;
extern lv_obj_t * ui_temperature1;
extern lv_obj_t * ui_temperaturelabel1;
extern lv_obj_t * ui_temperatureImage1;
extern lv_obj_t * ui_light1;
extern lv_obj_t * ui_lightlabel1;
extern lv_obj_t * ui_lightImage1;
extern lv_obj_t * ui_weather1;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_image1;
extern lv_obj_t * ui_season1;
extern lv_obj_t * ui_seasonimage1;
extern lv_obj_t * ui_seasonlabel1;
extern lv_obj_t * ui_firstplant;
void ui_event_Illustrated1(lv_event_t * e);
extern lv_obj_t * ui_Illustrated1;
void ui_event_next1(lv_event_t * e);
extern lv_obj_t * ui_next1;
extern lv_obj_t * ui_droplets1;
void ui_event_getseed1(lv_event_t * e);
extern lv_obj_t * ui_getseed1;
extern lv_obj_t * ui_getplanttextarea1;
void ui_event_plant1(lv_event_t * e);
extern lv_obj_t * ui_plant1;
extern lv_obj_t * ui_plantimg1;
extern lv_obj_t * ui_plantlabel1;
extern lv_obj_t * ui_seed;
extern lv_obj_t * ui_seed1;
extern lv_obj_t * ui_sprout1;
void ui_event_seeding1(lv_event_t * e);
extern lv_obj_t * ui_seeding1;
extern lv_obj_t * ui_mature1;
extern lv_obj_t * ui_flowering;
// SCREEN: ui_secondscreen
void ui_secondscreen_screen_init(void);
extern lv_obj_t * ui_secondscreen;
void ui_event_Insectremoval2(lv_event_t * e);
extern lv_obj_t * ui_Insectremoval2;
void ui_event_fertilize2(lv_event_t * e);
extern lv_obj_t * ui_fertilize2;
void ui_event_watering2(lv_event_t * e);
extern lv_obj_t * ui_watering2;
extern lv_obj_t * ui_health2;
extern lv_obj_t * ui_healthlabel2;
extern lv_obj_t * ui_healthImage2;
extern lv_obj_t * ui_state2;
extern lv_obj_t * ui_statelabel2;
extern lv_obj_t * ui_stateImage2;
extern lv_obj_t * ui_humidity2;
extern lv_obj_t * ui_humiditylabel2;
extern lv_obj_t * ui_humidityImage2;
extern lv_obj_t * ui_temperature2;
extern lv_obj_t * ui_temperaturelabel2;
extern lv_obj_t * ui_temperatureImage2;
extern lv_obj_t * ui_light2;
extern lv_obj_t * ui_lightlabel2;
extern lv_obj_t * ui_lightImage2;
extern lv_obj_t * ui_weather2;
extern lv_obj_t * ui_weatherlabel2;
extern lv_obj_t * ui_weatherimage2;
extern lv_obj_t * ui_season2;
extern lv_obj_t * ui_seasonimage2;
extern lv_obj_t * ui_seasonlabel2;
extern lv_obj_t * ui_secondplant2;
extern lv_obj_t * ui_Illustrated2;
extern lv_obj_t * ui_next2;
extern lv_obj_t * ui_droplets2;
void ui_event_getplant(lv_event_t * e);
extern lv_obj_t * ui_getplant;
extern lv_obj_t * ui_getplanttextarea2;
void ui_event_plant2(lv_event_t * e);
extern lv_obj_t * ui_plant2;
extern lv_obj_t * ui_plantimg2;
extern lv_obj_t * ui_plantlabel2;
extern lv_obj_t * ui_seed2;
void ui_event_prev2(lv_event_t * e);
extern lv_obj_t * ui_prev2;
// SCREEN: ui_IllustratedScreen1
void ui_IllustratedScreen1_screen_init(void);
extern lv_obj_t * ui_IllustratedScreen1;
extern lv_obj_t * ui_illustratedbg1;
extern lv_obj_t * ui_illuTextArea1;
extern lv_obj_t * ui_illuImage1;
extern lv_obj_t * ui_sunflower;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_IllustratedScreen2
void ui_IllustratedScreen2_screen_init(void);
extern lv_obj_t * ui_IllustratedScreen2;
extern lv_obj_t * ui_illustratedbg2;
extern lv_obj_t * ui_illuTextArea2;
extern lv_obj_t * ui_illuImage2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_back1_png);    // assets/back1.png
LV_IMG_DECLARE(ui_img_876520695);    // assets/盆栽植物_1749862881.png
LV_IMG_DECLARE(ui_img_bug_spray_png);    // assets/bug_spray.png
LV_IMG_DECLARE(ui_img_treefood_png);    // assets/TreeFood.png
LV_IMG_DECLARE(ui_img_wateringcan_png);    // assets/WateringCan.png
LV_IMG_DECLARE(ui_img_561135566);    // assets/红色爱心_1749806193.png
LV_IMG_DECLARE(ui_img_projectile_star_png);    // assets/Projectile_star.png
LV_IMG_DECLARE(ui_img_waterdrop_png);    // assets/waterdrop.png
LV_IMG_DECLARE(ui_img_1795366294);    // assets/温度计_1749799392.png
LV_IMG_DECLARE(ui_img_1138793207);    // assets/光照.png
LV_IMG_DECLARE(ui_img_1606731336);    // assets/袜子_1749805859.png
LV_IMG_DECLARE(ui_img_683165229);    // assets/盛开的花朵_1749806018.png
LV_IMG_DECLARE(ui_img_178160675);    // assets/卷轴与毛笔_1749798033.png
LV_IMG_DECLARE(ui_img_zen_nextgarden_png);    // assets/Zen_NextGarden.png
LV_IMG_DECLARE(ui_img_354690767);    // assets/水滴_1749819882.png
LV_IMG_DECLARE(ui_img_1745983305);    // assets/园艺师_1749865266.png
LV_IMG_DECLARE(ui_img_577302902);    // assets/妙蛙种子.png
LV_IMG_DECLARE(ui_img_seed1_png);    // assets/seed1.png
LV_IMG_DECLARE(ui_img_sprout1_png);    // assets/sprout1.png
LV_IMG_DECLARE(ui_img_seedling1_png);    // assets/seedling1.png
LV_IMG_DECLARE(ui_img_seedingframe1_png);    // assets/seedingframe1.png
LV_IMG_DECLARE(ui_img_mature1_png);    // assets/mature1.png
LV_IMG_DECLARE(ui_img_flowering1_png);    // assets/flowering1.png
LV_IMG_DECLARE(ui_img_zen_prevgarden_png);    // assets/Zen_PrevGarden.png
LV_IMG_DECLARE(ui_img_letterbg__png);    // assets/letterBG..png
LV_IMG_DECLARE(ui_img_uppercaveplants__png);    // assets/upperCavePlants..png
LV_IMG_DECLARE(ui_img_sunflower_png);    // assets/sunflower.png
LV_IMG_DECLARE(ui_img_2096096803);    // assets/包裹的礼物_1749863734.png
LV_IMG_DECLARE(ui_img_348401948);    // assets/萌芽_1749865223.png



LV_FONT_DECLARE(ui_font_FontPlant);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
