// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void insert_removal(lv_event_t * e);
void fertilize(lv_event_t * e);
void watering(lv_event_t * e);
void get_seed(lv_event_t * e);
void grow_plant(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
