// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void plant_insert_removal(lv_event_t * e);
void plant_fertilize(lv_event_t * e);
void plant_watering(lv_event_t * e);
void healthchange(lv_event_t * e);
void agechange(lv_event_t * e);
void humiditychange(lv_event_t * e);
void temperaturechange(lv_event_t * e);
void lightchange(lv_event_t * e);
void weatherchange(lv_event_t * e);
void seasonchange(lv_event_t * e);
void switch2illustratedscreen(lv_event_t * e);
void message_plantstage(lv_event_t * e);
void show_sunflowerseed(lv_event_t * e);
void growthstagechange(lv_event_t * e);
void show_sunflower2(lv_event_t * e);
void show_sunflower3(lv_event_t * e);
void show_sunflower4(lv_event_t * e);
void show_sunflower5(lv_event_t * e);
void show_sunflower6(lv_event_t * e);
void show_sunflower7(lv_event_t * e);
void show_message(lv_event_t * e);
void illu_img_change(lv_event_t * e);
void illu_label_change(lv_event_t * e);
void buy_sunflower(lv_event_t * e);
void buy_tomato(lv_event_t * e);
void buy_catus(lv_event_t * e);
void buy_cannibal(lv_event_t * e);
void show_money(lv_event_t * e);
void show_tomatoseed(lv_event_t * e);
void show_tomato2(lv_event_t * e);
void show_tomato3(lv_event_t * e);
void show_tomato4(lv_event_t * e);
void show_tomato5(lv_event_t * e);
void show_tomato6(lv_event_t * e);
void show_tomato7(lv_event_t * e);
void show_cactusseed(lv_event_t * e);
void show_cactus2(lv_event_t * e);
void show_cactus3(lv_event_t * e);
void show_cactus4(lv_event_t * e);
void show_cactus5(lv_event_t * e);
void show_cactus6(lv_event_t * e);
void show_cactus7(lv_event_t * e);
void get_seed(lv_event_t * e);
void show_cannibalseed(lv_event_t * e);
void show_canniabl2(lv_event_t * e);
void show_canniabl3(lv_event_t * e);
void show_canniabl4(lv_event_t * e);
void show_canniabl5(lv_event_t * e);
void show_canniabl6(lv_event_t * e);
void show_canniabl7(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
