// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void insert_removal(lv_event_t * e)
{
	// Your code here
}

void fertilize(lv_event_t * e)
{
	// Your code here
}

void watering(lv_event_t * e)
{
	// Your code here
}

void get_seed(lv_event_t * e)
{
	// Your code here
}

void grow_plant(lv_event_t * e)
{
	// Your code here
}
