// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_calculator;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button0(lv_event_t * e);
extern lv_obj_t * ui_Button0;
extern lv_obj_t * ui_Label0;
void ui_event_Buttonmul(lv_event_t * e);
extern lv_obj_t * ui_Buttonmul;
extern lv_obj_t * ui_Labelmul;
void ui_event_Buttondiv(lv_event_t * e);
extern lv_obj_t * ui_Buttondiv;
extern lv_obj_t * ui_Labeldiv;
void ui_event_Buttondel(lv_event_t * e);
extern lv_obj_t * ui_Buttondel;
extern lv_obj_t * ui_Labeldel;
void ui_event_Buttonadd(lv_event_t * e);
extern lv_obj_t * ui_Buttonadd;
extern lv_obj_t * ui_Labeladd;
void ui_event_Buttonsub(lv_event_t * e);
extern lv_obj_t * ui_Buttonsub;
extern lv_obj_t * ui_Labelsub;
void ui_event_Buttonequal(lv_event_t * e);
extern lv_obj_t * ui_Buttonequal;
extern lv_obj_t * ui_Labelequal;
extern lv_obj_t * ui_ioput;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
