// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void click7(lv_event_t * e);
void click8(lv_event_t * e);
void click9(lv_event_t * e);
void click4(lv_event_t * e);
void click5(lv_event_t * e);
void click6(lv_event_t * e);
void click1(lv_event_t * e);
void click2(lv_event_t * e);
void click3(lv_event_t * e);
void click0(lv_event_t * e);
void clickmul(lv_event_t * e);
void clickdiv(lv_event_t * e);
void clickdel(lv_event_t * e);
void clickadd(lv_event_t * e);
void clicksub(lv_event_t * e);
void clickequal(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
